Repository bratislava/olo.sk, pull requests merged in 2024-04, with the labels that each got.

#20 1/setup storybook
  next/.eslintrc.js
  next/.gitignore
  next/.storybook/main.ts
  next/.storybook/preview.ts
  next/package.json
  next/src/app/_components/storybook-test-components/BAButton/BAButton.stories.tsx
  next/src/app/_components/storybook-test-components/BAButton/BAButton.tsx
  next/src/app/_components/storybook-test-components/BAButton/MLink.tsx
  next/src/app/_components/storybook-test-components/BAButton/Spinner.tsx
  next/src/app/_components/storybook-test-components/BAButton/ui-icons/export.svg
  next/src/app/_components/storybook-test-components/BAButton/ui-icons/index.ts
  next/src/app/_components/storybook-test-components/BAButton/ui-icons/sipka-doprava.svg
  next/src/app/_components/storybook-test-components/TestButtonAppFolder.stories.tsx
  next/src/app/_components/storybook-test-components/TestButtonAppFolder.tsx
  next/tailwind.config.ts
  next/yarn.lock
Labels: pr: needs review :pray:

#26 ad pr labeler workflow
  .github/workflows/label.yml
Labels: pr: fix & ship :ship:

#28 update eslint and prettier
  next/.eslintrc.js
  next/.prettierrc.js
  next/src/app/_components/storybook-test-components/BAButton/BAButton.tsx
  next/src/app/_components/storybook-test-components/BAButton/Spinner.tsx
  next/src/app/_components/storybook-test-components/TestButtonAppFolder.tsx
  next/tailwind.config.ts
Labels: pr: fix & ship :ship:

#30 upgrade strapi to v4.22.1
  strapi/package.json
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#34 8/link
  next/src/app/_components/common/Icon/Icon.stories.tsx
  next/src/app/_components/common/Icon/Icon.tsx
  next/src/app/_components/common/Link/Link.stories.tsx
  next/src/app/_components/common/Link/Link.tsx
  next/src/app/page.tsx
Labels: pr: fix & ship :ship:

#36 added missing healthcheck page
  next/src/app/pages/api/healthcheck.ts
Labels: pr: fix & ship :ship:, pr: infrastructure

#37 Setup next.config, add generateImageSizes, add template image
  next/next.config.mjs
  next/src/app/_components/storybook-test-components/BAButton/BAButton.stories.tsx
  next/src/app/_components/storybook-test-components/BAButton/BAButton.tsx
  next/src/app/_components/storybook-test-components/BAButton/MLink.tsx
  next/src/app/_components/storybook-test-components/BAButton/Spinner.tsx
  next/src/app/_components/storybook-test-components/BAButton/ui-icons/export.svg
  next/src/app/_components/storybook-test-components/BAButton/ui-icons/index.ts
  next/src/app/_components/storybook-test-components/BAButton/ui-icons/sipka-doprava.svg
  next/src/app/_components/storybook-test-components/TestButtonAppFolder.stories.tsx
  next/src/app/_components/storybook-test-components/TestButtonAppFolder.tsx
  next/src/app/_utils/generateImageSizes.ts
  next/src/assets/images/olo-truck.jpg
Labels: pr: fix & ship :ship:

#40 fix healthcheck api endpoint to new app router syntax
  next/src/app/api/healthcheck/route.ts
  next/src/app/pages/api/healthcheck.ts
Labels: pr: needs review :pray:

#41 remove template text from readme
  README.md
Labels: pr: needs review :pray:

#38 implement Typography component #25
  next/src/app/_components/common/Typography/Typography.stories.tsx
  next/src/app/_components/common/Typography/Typography.tsx
  next/src/app/_components/common/Typography/normalizeSkText.ts
Labels: pr: fix & ship :ship:

#44 Fix colors setup
  next/tailwind.config.ts
Labels: pr: fix & ship :ship:

#45 Fix license fields
  next/package.json
  strapi/package.json
Labels: pr: fix & ship :ship:

#42 Add lint scripts to package.json
  next/package.json
Labels: pr: fix & ship :ship:

#43 Card Base, Article Card, Tag
  .vscode/settings.json
  next/.storybook/main.ts
  next/src/app/_components/common/Card/ArticleCard.stories.tsx
  next/src/app/_components/common/Card/ArticleCard.tsx
  next/src/app/_components/common/Card/CardBase.tsx
  next/src/app/_components/common/Tag/Tag.stories.tsx
  next/src/app/_components/common/Tag/Tag.tsx
  next/tailwind.config.ts
Labels: pr: fix & ship :ship:

#76 Basic content types #75
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/articles.gql
  next/src/services/graphql/queries/branches.gql
  next/src/services/graphql/queries/categories.gql
  next/src/services/graphql/queries/documents.gql
  next/src/services/graphql/queries/opening-times.gql
  next/src/services/graphql/queries/pages-queries.gql
  next/src/services/graphql/queries/tags.gql
  strapi/schema.graphql
  strapi/src/api/article/content-types/article/schema.json
  strapi/src/api/article/controllers/article.ts
  strapi/src/api/article/routes/article.ts
  strapi/src/api/article/services/article.ts
  strapi/src/api/branch/content-types/branch/schema.json
  strapi/src/api/branch/controllers/branch.ts
  strapi/src/api/branch/routes/branch.ts
  strapi/src/api/branch/services/branch.ts
  strapi/src/api/category/content-types/category/schema.json
  strapi/src/api/category/controllers/category.ts
  strapi/src/api/category/routes/category.ts
  strapi/src/api/category/services/category.ts
  strapi/src/api/contact/content-types/contact/schema.json
  strapi/src/api/contact/controllers/contact.ts
  strapi/src/api/contact/routes/contact.ts
  strapi/src/api/contact/services/contact.ts
  strapi/src/api/document/content-types/document/schema.json
  strapi/src/api/document/controllers/document.ts
  strapi/src/api/document/routes/document.ts
  strapi/src/api/document/services/document.ts
  strapi/src/api/opening-time/content-types/opening-time/schema.json
  strapi/src/api/opening-time/controllers/opening-time.ts
  strapi/src/api/opening-time/routes/opening-time.ts
  strapi/src/api/opening-time/services/opening-time.ts
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/api/tag/content-types/tag/schema.json
  strapi/src/api/tag/controllers/tag.ts
  strapi/src/api/tag/routes/tag.ts
  strapi/src/api/tag/services/tag.ts
  strapi/src/components/items/link.json
  strapi/src/components/items/opening-hours-item.json
  strapi/src/components/sections/section-1.json
  strapi/src/components/sections/section-2.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#52 50/cards-location-basic-category-faqcategory-listing
  next/src/app/_components/common/Card/ArticleCard.stories.tsx
  next/src/app/_components/common/Card/ArticleCard.tsx
  next/src/app/_components/common/Card/BasicCard.stories.tsx
  next/src/app/_components/common/Card/BasicCard.tsx
  next/src/app/_components/common/Card/CardBase.tsx
  next/src/app/_components/common/Card/CardImage.tsx
  next/src/app/_components/common/Card/CardLink.tsx
  next/src/app/_components/common/Card/CategoryCard.stories.tsx
  next/src/app/_components/common/Card/CategoryCard.tsx
  next/src/app/_components/common/Card/FaqCategoryCard.stories.tsx
  next/src/app/_components/common/Card/FaqCategoryCard.tsx
  next/src/app/_components/common/Card/ListingCard.stories.tsx
  next/src/app/_components/common/Card/ListingCard.tsx
  next/src/app/_components/common/Card/LocationCard.stories.tsx
  next/src/app/_components/common/Card/LocationCard.tsx
  next/src/app/_components/common/Icon/Icon.stories.tsx
  next/src/app/_components/common/Icon/Icon.tsx
  next/src/app/_components/common/ImagePlaceholder.tsx
  next/tailwind.config.ts
Labels: pr: fix & ship :ship:

#78 Fix ESlint error in Button
  next/src/app/_components/common/Button/Button.tsx
Labels: pr: fix & ship :ship:

#80 Add page header options as dynamic zone components
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/_common.gql
  next/src/services/graphql/queries/_header-sections.gql
  next/src/services/graphql/queries/pages.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/header-sections/branch-map.json
  strapi/src/components/header-sections/gallery.json
  strapi/src/components/header-sections/image.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#87 Setup cn function #21
  next/package.json
  next/src/app/_utils/cn.ts
  next/yarn.lock
Labels: pr: fix & ship :ship:

#86 50/cards sprint 3 part 2
  next/src/_components/common/Card/WasteSortingCard.stories.tsx
  next/src/_components/common/Card/WasteSortingCard.tsx
  next/src/_components/common/Card/WorkshopCard.stories.tsx
  next/src/_components/common/Icon/Icon.tsx
  next/src/_components/common/Icon/Pictogram.stories.tsx
  next/src/_components/common/Icon/Pictogram.tsx
  next/src/assets/pictograms/index.tsx
  next/src/assets/pictograms/waste-civic-amenity-site.svg
  next/src/assets/pictograms/waste-glass.svg
  next/src/assets/pictograms/waste-kitchen.svg
  next/src/assets/pictograms/waste-mixed.svg
  next/src/assets/pictograms/waste-oils-and-fats.svg
  next/src/assets/pictograms/waste-organic.svg
  next/src/assets/pictograms/waste-paper.svg
  next/src/assets/pictograms/waste-plastic.svg
  next/src/styles/colors.css
  next/tailwind.config.ts
Labels: pr: fix & ship :ship:

#90 Setup i18n #46
  next/i18next-parser.config.js
  next/next-i18next.config.js
  next/next.config.mjs
  next/package.json
  next/public/locales/sk/translation.json
  next/src/pages/_app.tsx
  next/src/pages/index.tsx
  next/src/pages/pages/[slug].tsx
  next/yarn.lock
Labels: pr: fix & ship :ship:

#91 Pagination basic #55
  next/.storybook/main.ts
  next/package.json
  next/src/_components/common/Button/Button.stories.tsx
  next/src/_components/common/Button/Button.tsx
  next/src/_components/common/Card/CardBase.tsx
  next/src/_components/common/Card/LocationCard.tsx
  next/src/_components/common/Card/WasteSortingCard.tsx
  next/src/_components/common/Pagination/Pagination.stories.tsx
  next/src/_components/common/Pagination/Pagination.tsx
  next/src/_components/common/Pagination/usePagination.ts
  next/src/styles/colors.css
  next/tailwind.config.ts
  next/yarn.lock
Labels: pr: fix & ship :ship:
