Repository bratislava/olo.sk, pull requests merged in 2024-09, with the labels that each got.

#451 #425 Update OpeningTimes section
  next/src/components/common/OpeningHoursBox.tsx
  next/src/components/sections/OpeningTimesSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/components/items/opening-times-item.json
  strapi/src/components/sections/opening-times.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#449 #423 listing cards fixes
  next/src/components/common/Card/ListingCard.tsx
  next/src/components/sections/CardsListSection.tsx
  next/src/components/sections/FaqCategoriesSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/components/items/cards-list-item.json
  strapi/src/components/sections/cards-list.json
  strapi/types/generated/components.d.ts
Labels: pr: needs review :pray:

#448 #399 Add alert message to SortingGuide
  next/src/components/common/Accordion/WasteSortingGuide.stories.tsx
  next/src/components/common/Accordion/WasteSortingGuide.tsx
  next/src/components/sections/SortingGuideSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/styles/colors.css
  next/tailwind.config.ts
  strapi/schema.graphql
  strapi/src/components/items/sorting-guide-alert-message.json
  strapi/src/components/items/sorting-guide.json
  strapi/types/generated/components.d.ts
Labels: pr: needs review :pray:

#455 Refactor navigation middleware
  next/src/components/common/Accordion/WasteSortingGuide.tsx
  next/src/components/sections/hompage/HeroHomepageSection.tsx
  next/src/components/sections/hompage/ServicesHomepageSection.tsx
  next/src/middleware.ts
  next/src/pages/[...path].tsx
  next/src/pages/api/navigation.ts
  next/src/pages/api/sitemap/[...pathname].ts
  next/src/pages/articles/[slug].tsx
  next/src/pages/documents/[slug].tsx
  next/src/pages/faq-categories/[slug].tsx
  next/src/pages/index.tsx
  next/src/pages/services/[slug].tsx
  next/src/pages/workshops/[slug].tsx
  next/src/providers/GeneralContextProvider.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_general.gql
  next/src/services/graphql/queries/articles.gql
  next/src/services/graphql/queries/documents.gql
  next/src/services/graphql/queries/pages.gql
  next/src/services/graphql/queries/services.gql
  next/src/services/graphql/queries/workshops.gql
  next/src/services/navigation/fetchNavigation.ts
  next/src/services/navigation/getNavigationMiddleware.ts
  next/src/services/navigation/parseContentTypePathPrefixes.ts
  next/src/services/navigation/parseTopLevelPages.ts
  next/src/services/navigation/typesNavigation.ts
  next/src/utils/getPagePath.ts
  next/src/utils/useGetFullPath.ts
  strapi/package.json
Labels: pr: needs review :pray:

#450 #402 Embed Mapbox
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/.env.example
  next/next.config.mjs
  next/package.json
  next/yarn.lock
Labels: pr: fix & ship :ship:

#459 #347 Implement static generation for Pages along with alias redirect
  next/public/locales/sk/translation.json
  next/src/components/sections/AliasSection.tsx
  next/src/pages/[...path].tsx
Labels: pr: fix & ship :ship:

#461 #392 Add Branch details
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/branches.gql
  strapi/schema.graphql
  strapi/src/api/branch/content-types/branch/schema.json
  strapi/src/api/contact/content-types/contact/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/opening-times.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#462 #406 Add Vacancies section placeholder
  next/src/components/layout/Sections.tsx
  next/src/components/sections/VacanciesSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/table.json
  strapi/src/components/sections/vacancies.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#464 #463 Prefetch sections data
  next/src/components/sections/FaqCategoriesSection.tsx
  next/src/components/sections/ServicesSection.tsx
  next/src/components/sections/headers/PageHeaderPickupDay.tsx
  next/src/pages/[...path].tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_categories-and-tags.gql
  next/src/services/graphql/queries/services.gql
  next/src/utils/prefetchPageSections.ts
Labels: pr: fix & ship :ship:

#452 #334 Richtext insert newline after image
  strapi/src/plugins/wysiwyg/admin/src/components/Wysiwyg/index.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#470 #468 Fetch latest articles on Homepage
  next/src/components/sections/hompage/ArticlesHomepageSection.tsx
Labels: pr: needs review :pray:

#457 Add search page (WIP)
  next/public/locales/sk/translation.json
  next/src/components/common/Card/MenuItemArticleCard.tsx
  next/src/components/common/Card/SearchResultRowCard.stories.tsx
  next/src/components/common/Card/SearchResultRowCard.tsx
  next/src/components/common/Chip/Chip.tsx
  next/src/components/common/NavBar/NavBarHeader/NavBarHeader.tsx
  next/src/components/common/NavBar/NavMenu/NavMenu.tsx
  next/src/components/common/SearchBar/SearchBar.tsx
  next/src/components/common/SearchResults/SearchResults.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/ArticlesSection.tsx
  next/src/components/sections/DocumentsAllSection.tsx
  next/src/components/sections/GlobalSearchSection.tsx
  next/src/components/sections/ServicesSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/menu.gql
  next/src/services/graphql/queries/pages.gql
  next/src/services/meili/fetchers/pagesFetcher.ts
  next/src/services/meili/types.ts
  next/src/utils/useQueryBySearchOption.ts
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/items/menu-header.json
  strapi/src/components/sections/global-search.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#477 Fix subscript and superscript rendering in Markdown
  next/package.json
  next/src/components/formatting/Markdown.tsx
  next/yarn.lock
Labels: pr: needs review :pray:

#478 Fix card height when in row, add title to CardBase when title is line-clamped
  next/src/components/common/Card/BasicCard.stories.tsx
  next/src/components/common/Card/BasicCard.tsx
  next/src/components/common/Card/BranchCard.tsx
  next/src/components/common/Card/FaqCategoryCard.tsx
  next/src/components/common/Card/ListingCard.tsx
  next/src/components/common/Card/ServiceCard.tsx
  next/src/components/common/Card/WorkshopCard.tsx
  next/src/components/sections/BranchesSection.tsx
  next/src/components/sections/CardSliderSection.tsx
  next/src/components/sections/FaqCategoriesSection.tsx
  next/src/components/sections/WorkshopsSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/components/items/card-slider-card.json
  strapi/types/generated/components.d.ts
Labels: pr: needs review :pray:

#492 #491 Finish navigation middleware rewrite
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/src/components/placeholder/usePlaceholderMenuData.ts
  next/src/components/sections/TableSection.tsx
  next/src/environment.ts
  next/src/middleware.ts
  next/src/pages/[...path].tsx
  next/src/pages/api/navigation.ts
  next/src/pages/articles/[slug].tsx
  next/src/pages/documents/[slug].tsx
  next/src/pages/faq-categories/[slug].tsx
  next/src/pages/form.tsx
  next/src/pages/index.tsx
  next/src/pages/services/[slug].tsx
  next/src/pages/workshops/[slug].tsx
  next/src/providers/GeneralContextProvider.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_general.gql
  next/src/services/graphql/queries/pages.gql
  next/src/services/navigation/fetchNavigation.ts
  next/src/services/navigation/fetchNonCachedNavigation.ts
  next/src/services/navigation/fetchNonCachedNavigationFromApi.ts
  next/src/services/navigation/getNavigationMiddleware.ts
  next/src/services/navigation/navigationConfig.ts
  next/src/services/navigation/parseContentTypePathPrefixes.ts
  next/src/services/navigation/parseTopLevelPages.ts
  next/src/services/navigation/typesNavigation.ts
  next/src/utils/getPageBreadcrumbs.ts
  next/src/utils/useGetFullPath.ts
  strapi/config/plugins.meilisearch.config.ts
Labels: pr: fix & ship :ship:

#499 #422 Fetch menu and footer on client + prefetch
  next/src/components/common/Footer/DesktopFooter.tsx
  next/src/components/common/Footer/FooterShared.tsx
  next/src/components/common/Footer/MobileFooter.tsx
  next/src/components/common/NavBar/NavBarHeader/NavBarHeader.tsx
  next/src/components/common/NavBar/NavMenu/NavMenu.tsx
  next/src/pages/[...path].tsx
  next/src/pages/_app.tsx
  next/src/pages/articles/[slug].tsx
  next/src/pages/documents/[slug].tsx
  next/src/pages/faq-categories/[slug].tsx
  next/src/pages/index.tsx
  next/src/pages/services/[slug].tsx
  next/src/pages/workshops/[slug].tsx
  next/src/utils/prefetchPageSections.ts
  next/src/utils/queryOptions.ts
Labels: pr: fix & ship :ship:

#466 #186 Refactor divider behaviour in Mega Menu
  next/src/components/common/Card/MenuItemArticleCard.stories.tsx
  next/src/components/common/Card/MenuItemArticleCard.tsx
  next/src/components/common/Card/MenuItemBranchCard.stories.tsx
  next/src/components/common/Card/MenuItemWorkshopCard.stories.tsx
  next/src/components/common/Card/MenuItemWorkshopCard.tsx
  next/src/components/common/NavBar/NavBarDivider.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuContent.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuContentCell.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuLatestArticlesList.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuSingleColumnList.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuTwoColumnList.tsx
  next/src/utils/useLatestArticles.ts
Labels: pr: fix & ship :ship:

#501 #500 Add revalidate to notFound objects in getStaticProps
  next/src/pages/[...path].tsx
  next/src/pages/articles/[slug].tsx
  next/src/pages/documents/[slug].tsx
  next/src/pages/faq-categories/[slug].tsx
  next/src/pages/index.tsx
  next/src/pages/services/[slug].tsx
  next/src/pages/workshops/[slug].tsx
  next/src/services/navigation/getNavigationMiddleware.ts
  next/src/utils/conts.ts
Labels: pr: fix & ship :ship:

#503 #497 Add service relation to MenuLink
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/menu.gql
  strapi/schema.graphql
  strapi/src/components/menu/menu-link.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#506 #505 Prefetch latest articles in menu
  next/src/components/common/NavBar/NavMenu/NavMenuLatestArticlesList.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
  next/src/pages/[...path].tsx
  next/src/pages/articles/[slug].tsx
  next/src/pages/documents/[slug].tsx
  next/src/pages/faq-categories/[slug].tsx
  next/src/pages/index.tsx
  next/src/pages/services/[slug].tsx
  next/src/pages/workshops/[slug].tsx
  next/src/utils/queryOptions.ts
  next/src/utils/useLatestArticles.ts
Labels: pr: fix & ship :ship:

#510 #509 Implement revalidate endpoint
  next/.env.example
  next/kubernetes/base/deployment.yml
  next/kubernetes/envs/Dev/kustomization.yml
  next/kubernetes/envs/Dev/secrets/revalidate.secret.yml
  next/kubernetes/envs/Prod/kustomization.yml
  next/kubernetes/envs/Prod/secrets/revalidate.secret.yml
  next/kubernetes/envs/Staging/kustomization.yml
  next/kubernetes/envs/Staging/secrets/revalidate.secret.yml
  next/src/pages/api/revalidate.ts
Labels: pr: fix & ship :ship:

#511 #485 Add `alias` also for articles
  next/kubernetes/envs/Dev/secrets/revalidate.secret.yml
  next/kubernetes/envs/Prod/secrets/revalidate.secret.yml
  next/kubernetes/envs/Staging/secrets/revalidate.secret.yml
  next/public/locales/sk/translation.json
  next/src/components/sections/AliasInfoMessage.tsx
  next/src/components/sections/AliasSection.tsx
  next/src/pages/[...path].tsx
  next/src/pages/api/revalidate.ts
  next/src/pages/articles/[slug].tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/articles.gql
  next/src/services/graphql/queries/pages.gql
  strapi/schema.graphql
  strapi/src/api/article/content-types/article/schema.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#494 #401 KOLO branches map section
  next/src/assets/markers/map-marker-default.svg
  next/src/assets/markers/map-marker-kolo.svg
  next/src/components/common/Card/BranchCard.tsx
  next/src/components/common/Icon/OloMarker.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/BranchesMapSection.stories.tsx
  next/src/components/sections/BranchesMapSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_header-sections.gql
  next/src/services/graphql/queries/_page-sections.gql
  next/src/utils/getBoundsForBranches.ts
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/branches-map.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#515 Cleanup BranchSections from redundant components
  next/src/components/common/BranchesMap/BranchesMap.tsx
  next/src/components/common/Card/BranchCard.tsx
  next/src/components/layout/PageHeaderSections.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/BranchesMapSection.stories.tsx
  next/src/components/sections/BranchesMapSection.tsx
  next/src/components/sections/BranchesSection.tsx
  next/src/components/sections/headers/PageHeaderBranchMap.stories.tsx
  next/src/components/sections/headers/PageHeaderBranchMap.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_header-sections.gql
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/branches-map.json
  strapi/src/components/sections/branches.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#520 #493 Use `plugin:react/recommended` in eslint settings and fix errors
  next/.eslintrc.js
  next/src/components/common/Box/DirectionsBox.stories.tsx
  next/src/components/common/Button/Button.stories.tsx
  next/src/components/common/Card/CardBase.stories.tsx
  next/src/components/common/Card/ServiceCard.stories.tsx
  next/src/components/common/Card/ServiceCard.tsx
  next/src/components/common/Card/WasteSortingCard.stories.tsx
  next/src/components/common/Carousel/Carousel.stories.tsx
  next/src/components/common/Icon/Icon.stories.tsx
  next/src/components/common/Icon/OloIcon.stories.tsx
  next/src/components/common/Icon/Pictogram.stories.tsx
  next/src/components/common/Sidebar/SidebarCareer.stories.tsx
  next/src/components/common/Typography/Typography.stories.tsx
  next/src/components/sections/ColumnsListSection.tsx
  next/src/components/sections/ColumnsSection.tsx
  next/src/components/sections/ContactsSection.tsx
  next/src/components/sections/DocumentsAllSection.tsx
  next/src/components/sections/OpeningTimesSection.tsx
  next/src/components/sections/SortingGuideAccordionsSection.tsx
  next/src/components/sections/headers/PageHeaderFeaturedNews.tsx
  next/src/components/sections/headers/PageHeaderGallery.tsx
  next/src/components/sections/headers/PageHeaderPickupDay.tsx
  next/src/pages/[...path].tsx
  next/src/services/meili/meiliClient.ts
Labels: pr: fix & ship :ship:

#521 #482 Modify ordered cards
  next/src/components/sections/OrderedCardsSection.tsx
  next/src/services/graphql/api.ts
  strapi/schema.graphql
  strapi/src/components/items/ordered-cards-item.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#522 #489 Replace two buttons with a single link in ImageAndTextOverlappedSection
  next/src/components/sections/ImageAndTextOverlappedSection.stories.tsx
  next/src/components/sections/ImageAndTextOverlappedSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/components/sections/image-and-text-overlapped.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#525 #311 Rename SidebarDivider to Divider
  next/src/components/common/Accordion/AccordionGroup.tsx
  next/src/components/common/BranchesMap/BranchesMap.tsx
  next/src/components/common/Card/ServicesTile.tsx
  next/src/components/common/Sidebar/Divider.tsx
  next/src/components/common/Sidebar/SidebarCareer.tsx
  next/src/components/common/Sidebar/SidebarContacts.tsx
  next/src/components/page-contents/document/DocumentPageContent.tsx
  next/src/components/sections/ArticlesSection.tsx
  next/src/components/sections/DividerSection.tsx
  next/src/components/sections/hompage/KoloHomepageSection.tsx
Labels: pr: fix & ship :ship:

#523 #486 Display perex for articles
  next/src/pages/articles/[slug].tsx
Labels: pr: fix & ship :ship:

#526 #513 Fix image overlap with z-index
  next/src/components/sections/headers/PageHeaderSideImage.stories.tsx
  next/src/components/sections/headers/PageHeaderSideImage.tsx
Labels: pr: fix & ship :ship:

#524 #314 Rename hompage folder to homepage
  next/src/components/sections/homepage/ArticlesHomepageSection.tsx
  next/src/components/sections/homepage/HeroHomepageSection.tsx
  next/src/components/sections/homepage/KoloHomepageSection.tsx
  next/src/components/sections/homepage/ServicesHomepageSection.tsx
  next/src/pages/index.tsx
Labels: pr: fix & ship :ship:

#465 #453 Add color token for success, warning and error
  next/src/components/common/Accordion/WasteSortingGuide.tsx
  next/src/components/common/Tag/Tag.tsx
  next/src/styles/colors.css
  next/tailwind.config.ts
Labels: pr: fix & ship :ship:

#529 #527 Add missing NEXT_PUBLIC_NEXT_HOST variable to .env.example
  next/.env.example
Labels: pr: fix & ship :ship:

#322 #255 Richtext - links for OLO content types
  next/package.json
  next/src/components/formatting/Markdown.tsx
  next/src/components/formatting/useTransformOloMarkdownLinks.ts
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/articles.gql
  next/src/services/graphql/queries/documents.gql
  next/src/services/graphql/queries/pages.gql
  next/src/services/graphql/queries/services.gql
  next/src/services/graphql/queries/workshops.gql
  next/yarn.lock
Labels: pr: fix & ship :ship:, pr: question :question:

#528 #141 Create homepage Slider
  next/src/assets/images/index.ts
  next/src/assets/images/olo-placeholder-map.jpg
  next/src/assets/images/placeholder-abstract-background.png
  next/src/components/common/Banner/Banner.stories.tsx
  next/src/components/common/MapPlaceholder.tsx
  next/src/components/common/Slider/Slider.stories.tsx
  next/src/components/common/Slider/Slider.tsx
  next/src/components/sections/homepage/HeroHomepageSection.tsx
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#549 Persist dockerized postgres data locally
  .gitignore
  docker-compose.yml
Labels: pr: fix & ship :ship:

#550 #536 Add Forms content type
  next/src/components/common/FormCtaBanner/FormCtaBanner.tsx
  next/src/pages/[...path].tsx
  next/src/pages/form/[slug].tsx
  next/src/pages/form/index.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_common.gql
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/forms.gql
  next/src/services/navigation/getNavigationMiddleware.ts
  next/src/utils/useGetLinkProps.ts
  strapi/schema.graphql
  strapi/src/api/form/content-types/form/schema.json
  strapi/src/api/form/controllers/form.ts
  strapi/src/api/form/routes/form.ts
  strapi/src/api/form/services/form.ts
  strapi/src/components/items/form-cta-banner-link.json
  strapi/src/components/sections/form-cta-banner.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#544 #467 globalsearch finishing touches
  next/public/locales/sk/translation.json
  next/src/assets/pictograms/dokumenty.svg
  next/src/assets/pictograms/index.tsx
  next/src/assets/pictograms/transparentne-mesto.svg
  next/src/components/common/Card/CardBase.tsx
  next/src/components/common/Card/SearchResultRowCard.tsx
  next/src/components/common/Icon/Pictogram.tsx
  next/src/components/common/SearchResults/SearchResults.tsx
  next/src/components/sections/GlobalSearchSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/services.gql
  next/src/services/meili/fetchers/servicesFetcher.ts
  next/src/utils/useQueryBySearchOption.ts
  strapi/config/plugins.meilisearch.config.ts
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#570 Minor fixes
  next/src/components/common/Box/BranchMap.tsx
  next/src/components/common/Card/BranchCard.tsx
  next/src/components/sections/headers/PageHeaderGallery.tsx
  next/src/utils/useGetLinkProps.ts
Labels: pr: fix & ship :ship:

#552 #484 Adjust UI after making board members' image optional
  next/src/components/common/BoardMemberRowGroup/BoardMemberRowGroup.stories.tsx
  next/src/components/common/BoardMemberRowGroup/BoardMemberRowGroup.tsx
  next/src/components/common/Card/BoardMemberRowCard.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#548 #141 Handle color contrast issues in Slider
  next/package.json
  next/src/components/common/Slider/Slider.stories.tsx
  next/src/components/common/Slider/Slider.tsx
  next/src/components/sections/homepage/HeroHomepageSection.tsx
  next/src/services/graphql/api.ts
  next/yarn.lock
  strapi/schema.graphql
  strapi/src/components/items/slide.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#582 #407 Add custom plugin to import WasteCollectionDays
  next/src/components/layout/Sections.tsx
  next/src/components/sections/WasteCollectionDays.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/waste-collection-days.gql
  next/src/services/meili/fetchers/wasteCollectionDaysFetcher.ts
  next/src/services/meili/types.ts
  strapi/.strapi/client/app.js
  strapi/Dockerfile
  strapi/README.md
  strapi/config/plugins.meilisearch.config.ts
  strapi/config/plugins.ts
  strapi/package.json
  strapi/patches/strapi-plugin-meilisearch+0.9.2.patch
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/api/waste-collection-day/content-types/waste-collection-day/schema.json
  strapi/src/api/waste-collection-day/controllers/waste-collection-day.ts
  strapi/src/api/waste-collection-day/routes/waste-collection-day.ts
  strapi/src/api/waste-collection-day/services/waste-collection-day.ts
  strapi/src/components/sections/waste-collection-days.json
  strapi/src/plugins/waste-collection-days-import/README.md
  strapi/src/plugins/waste-collection-days-import/admin/src/components/ImportSection.tsx
  strapi/src/plugins/waste-collection-days-import/admin/src/components/Initializer/index.tsx
  strapi/src/plugins/waste-collection-days-import/admin/src/components/PluginIcon/index.tsx
  strapi/src/plugins/waste-collection-days-import/admin/src/index.tsx
  strapi/src/plugins/waste-collection-days-import/admin/src/pages/App/index.tsx
  strapi/src/plugins/waste-collection-days-import/admin/src/pages/HomePage/index.tsx
  strapi/src/plugins/waste-collection-days-import/admin/src/pluginId.ts
  strapi/src/plugins/waste-collection-days-import/admin/src/utils/axiosInstance.ts
  strapi/src/plugins/waste-collection-days-import/custom.d.ts
  strapi/src/plugins/waste-collection-days-import/package.json
  strapi/src/plugins/waste-collection-days-import/server/bootstrap.ts
  strapi/src/plugins/waste-collection-days-import/server/config/index.ts
  strapi/src/plugins/waste-collection-days-import/server/content-types/index.ts
  strapi/src/plugins/waste-collection-days-import/server/controllers/index.ts
  strapi/src/plugins/waste-collection-days-import/server/destroy.ts
  strapi/src/plugins/waste-collection-days-import/server/helpers/parse-waste-collection-days-xlsx.ts
  strapi/src/plugins/waste-collection-days-import/server/index.ts
  strapi/src/plugins/waste-collection-days-import/server/middlewares/index.ts
  strapi/src/plugins/waste-collection-days-import/server/policies/index.ts
  strapi/src/plugins/waste-collection-days-import/server/register.ts
  strapi/src/plugins/waste-collection-days-import/server/routes/index.ts
  strapi/src/plugins/waste-collection-days-import/server/services/index.ts
  strapi/src/plugins/waste-collection-days-import/server/services/my-service.ts
  strapi/src/plugins/waste-collection-days-import/strapi-admin.js
  strapi/src/plugins/waste-collection-days-import/strapi-server.js
  strapi/src/plugins/waste-collection-days-import/tsconfig.json
  strapi/src/plugins/waste-collection-days-import/tsconfig.server.json
  strapi/src/plugins/waste-collection-days-import/yarn.lock
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
  strapi/yarn.lock
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#546 #532 Implement Table of contents in Service detail page
  next/package.json
  next/public/locales/sk/translation.json
  next/src/components/common/Accordion/Accordion.tsx
  next/src/components/common/TableOfContents/Content.tsx
  next/src/components/common/TableOfContents/DesktopTableOfContents.tsx
  next/src/components/common/TableOfContents/MobileTableOfContents.tsx
  next/src/components/common/TableOfContents/useHeadings.ts
  next/src/components/common/Typography/Typography.tsx
  next/src/components/layout/Section/SectionContainer.tsx
  next/src/components/page-contents/service/ServicePageContent.tsx
  next/src/pages/_app.tsx
  next/yarn.lock
Labels: pr: fix & ship :ship:

#586 #568 ContactsSection redesign
  next/public/locales/sk/translation.json
  next/src/assets/pictograms/doprava-a-mapy.svg
  next/src/assets/pictograms/index.tsx
  next/src/components/common/ContactBox.tsx
  next/src/components/common/Icon/Pictogram.tsx
  next/src/components/common/OpeningTimesChangeAlert.tsx
  next/src/components/sections/ContactsSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/articles.gql
  next/src/styles/colors.css
  next/tailwind.config.ts
  strapi/schema.graphql
  strapi/src/api/article/content-types/article/schema.json
  strapi/src/components/items/contacts-branch.json
  strapi/src/components/items/contacts-contact.json
  strapi/src/components/items/contacts-opening-time.json
  strapi/src/components/sections/contacts.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#590 #588 Remove for cyclus from package.json
  strapi/package.json
Labels: pr: fix & ship :ship:

#589 #407 Add options to delete collection days by type and update meili index
  strapi/src/plugins/waste-collection-days-import/admin/src/components/DeleteSection.tsx
  strapi/src/plugins/waste-collection-days-import/admin/src/components/UpdateMeilisearchSection.tsx
  strapi/src/plugins/waste-collection-days-import/admin/src/index.tsx
  strapi/src/plugins/waste-collection-days-import/admin/src/pages/HomePage/index.tsx
  strapi/src/plugins/waste-collection-days-import/server/controllers/index.ts
  strapi/src/plugins/waste-collection-days-import/server/routes/index.ts
Labels: pr: fix & ship :ship:

#594 #593 Fix ArticlesSection pageSize
  next/src/components/sections/ArticlesSection.tsx
  next/src/services/meili/fetchers/articlesFetcher.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#560 #386 Create header for Careers page
  next/src/components/common/Image/ImageAndTextOverlapped.stories.tsx
  next/src/components/common/Image/ImageAndTextOverlapped.tsx
  next/src/components/common/Video/Video.stories.tsx
  next/src/components/common/Video/Video.tsx
  next/src/components/layout/PageHeaderSections.tsx
  next/src/components/sections/ImageAndTextOverlappedSection.tsx
  next/src/components/sections/headers/CareersPageHeader.stories.tsx
  next/src/components/sections/headers/CareersPageHeader.tsx
  next/src/components/sections/headers/PageHeaderGallery.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_header-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/header-sections/careers.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:
