Repository bratislava/olo.sk, pull requests merged in 2024-10, with the labels that each got.

#601 #295 Add sidebar dynamic zone to Pages
  next/public/locales/sk/translation.json
  next/src/components/common/Card/BasicRowCard.tsx
  next/src/components/common/Sidebar/SidebarContacts.tsx
  next/src/components/layout/PageHeaderSections.tsx
  next/src/components/layout/Sidebars.tsx
  next/src/components/page-contents/service/ServicePageContent.tsx
  next/src/components/sections/AliasInfoMessage.tsx
  next/src/components/sidebars/ContactsSidebar.tsx
  next/src/pages/[...path].tsx
  next/src/pages/services/[slug].tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sidebars.gql
  next/src/services/graphql/queries/branches.gql
  next/src/services/graphql/queries/pages.gql
  strapi/schema.graphql
  strapi/src/api/branch/content-types/branch/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sidebars/contacts-sidebar.json
  strapi/src/components/sidebars/empty-sidebar.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#598 #540 Install and use `@strapi/plugin-seo`
  next/public/locales/sk/translation.json
  next/src/components/common/Card/BasicRowCard.tsx
  next/src/components/common/SeoHead.tsx
  next/src/components/common/Sidebar/SidebarContacts.tsx
  next/src/components/layout/PageHeaderSections.tsx
  next/src/components/layout/Sidebars.tsx
  next/src/components/page-contents/service/ServicePageContent.tsx
  next/src/components/sections/AliasInfoMessage.tsx
  next/src/components/sidebars/ContactsSidebar.tsx
  next/src/pages/[...path].tsx
  next/src/pages/services/[slug].tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sidebars.gql
  next/src/services/graphql/queries/branches.gql
  next/src/services/graphql/queries/pages.gql
  next/src/services/graphql/queries/seo.gql
  next/src/services/graphql/queries/services.gql
  strapi/.strapi/client/app.js
  strapi/package.json
  strapi/schema.graphql
  strapi/src/api/branch/content-types/branch/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/api/service/content-types/service/schema.json
  strapi/src/components/shared/meta-social.json
  strapi/src/components/shared/seo.json
  strapi/src/components/sidebars/contacts-sidebar.json
  strapi/src/components/sidebars/empty-sidebar.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#599 #583 Adjust slider height
  next/src/components/common/Slider/Slider.tsx
  next/src/components/sections/homepage/HeroHomepageSection.tsx
Labels: pr: fix & ship :ship:

#602 #603 olo namespace setup
  .github/workflows/deploy.yml
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/kubernetes/base/deployment.yml
  next/kubernetes/envs/Dev/.env
  next/kubernetes/envs/Dev/kustomization.yml
  next/kubernetes/envs/Dev/secrets/nalgoo.secret.yml
  next/kubernetes/envs/Dev/secrets/revalidate.secret.yml
  next/kubernetes/envs/Prod/.env
  next/kubernetes/envs/Prod/config.json
  next/kubernetes/envs/Prod/kustomization.yml
  next/kubernetes/envs/Prod/secrets/nalgoo.secret.yml
  next/kubernetes/envs/Prod/secrets/revalidate.secret.yml
  next/kubernetes/envs/Staging/.env
  next/kubernetes/envs/Staging/kustomization.yml
  next/kubernetes/envs/Staging/secrets/nalgoo.secret.yml
  next/kubernetes/envs/Staging/secrets/revalidate.secret.yml
  strapi/kubernetes/base/deployment.yml
  strapi/kubernetes/envs/Dev/kustomization.yml
  strapi/kubernetes/envs/Dev/secrets/database.secret.yml
  strapi/kubernetes/envs/Dev/secrets/meilisearch.secret.yml
  strapi/kubernetes/envs/Dev/secrets/strapi.secret.yml
  strapi/kubernetes/envs/Prod/kustomization.yml
  strapi/kubernetes/envs/Prod/secrets/database.secret.yml
  strapi/kubernetes/envs/Prod/secrets/meilisearch.secret.yml
  strapi/kubernetes/envs/Prod/secrets/strapi.secret.yml
  strapi/kubernetes/envs/Staging/kustomization.yml
  strapi/kubernetes/envs/Staging/secrets/database.secret.yml
  strapi/kubernetes/envs/Staging/secrets/meilisearch.secret.yml
  strapi/kubernetes/envs/Staging/secrets/strapi.secret.yml
Labels: pr: fix & ship :ship:

#608 #462 Section CareerPositions list
  next/.env.example
  next/.eslintrc.js
  next/openapitools.json
  next/package.json
  next/public/locales/sk/translation.json
  next/src/components/common/Card/JobPositionRowCard.tsx
  next/src/components/sections/VacanciesSection.tsx
  next/src/pages/api/nalgoo.ts
  next/src/services/nalgoo/fetchOpenPositions.ts
  next/src/services/nalgoo/fetchOpenPositionsFromApi.ts
  next/src/services/todo-openapi-nalgoo/.gitignore
  next/src/services/todo-openapi-nalgoo/.npmignore
  next/src/services/todo-openapi-nalgoo/.openapi-generator-ignore
  next/src/services/todo-openapi-nalgoo/.openapi-generator/FILES
  next/src/services/todo-openapi-nalgoo/.openapi-generator/VERSION
  next/src/services/todo-openapi-nalgoo/api.ts
  next/src/services/todo-openapi-nalgoo/base.ts
  next/src/services/todo-openapi-nalgoo/common.ts
  next/src/services/todo-openapi-nalgoo/configuration.ts
  next/src/services/todo-openapi-nalgoo/git_push.sh
  next/src/services/todo-openapi-nalgoo/index.ts
  next/yarn.lock
Labels: pr: fix & ship :ship:

#604 Add faqCategories field
  next/src/components/sections/FaqSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/components/sections/faq.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#595 Implement fetching articles by selected tags
  next/src/components/sections/headers/PageHeaderPickupDay.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_header-sections.gql
  next/src/services/graphql/queries/articles.gql
  strapi/schema.graphql
  strapi/src/components/header-sections/pickup-day.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#614 updated comment
  .github/workflows/deploy.yml
Labels: pr: fix & ship :ship:

#622 #616 Remove divider if seeAllLink is not provided in Strapi
  next/src/components/common/NavBar/NavMenu/NavMenuContent.tsx
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#627 #384 Section - waste removal cards
  next/src/components/common/Card/BasicCard.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/WasteRemovalCardsSection.stories.tsx
  next/src/components/sections/WasteRemovalCardsSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/services.gql
  strapi/schema.graphql
  strapi/src/api/service/content-types/service/schema.json
  strapi/src/components/sections/waste-removal-cards.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#610 Remove TableSection (= Odvozove dni placeholder section)
  next/src/components/layout/Sections.tsx
  next/src/components/sections/TableSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/table.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#644 481 card slider remove line clamp
  next/src/components/common/Card/BasicCard.tsx
  next/src/components/sections/WasteCollectionDays.tsx
Labels: pr: fix & ship :ship:

#641 Pipeline docker.com login
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: pr: fix & ship :ship:

#646 Bump strapi memory limit to 1Gi on staging and dev
  strapi/kubernetes/envs/Dev/config.json
  strapi/kubernetes/envs/Staging/config.json
Labels: pr: fix & ship :ship:

#637 #573 Waste collection points section
  next/src/components/common/Card/LocationCard.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/WasteCollectionPointsSection.stories.tsx
  next/src/components/sections/WasteCollectionPointsSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/items/location-cards-item.json
  strapi/src/components/sections/waste-collection-points.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#647 #574 Add image field to branch entity
  next/src/components/common/BranchesMap/BranchesMap.tsx
  next/src/components/sections/BranchesSection.tsx
  next/src/components/sections/homepage/KoloHomepageSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/branches.gql
  strapi/schema.graphql
  strapi/src/api/branch/content-types/branch/schema.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#659 Fix table styling in WasteCollectionDays
  next/src/components/sections/WasteCollectionDays.tsx
Labels: pr: fix & ship :ship:

#653 Refactor FormCtaBanner
  next/src/components/common/FormCtaBanner/FormCtaBanner.tsx
  next/src/components/sections/FormCtaBannerSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/components/sections/form-cta-banner.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#673 Add new Material design icons for use in homepage tiles
  next/src/assets/icons-olo/index.ts
  next/src/assets/icons-olo/local-parking.svg
  next/src/assets/icons-olo/material-brush.svg
  next/src/assets/icons-olo/material-compost.svg
  next/src/assets/icons-olo/material-home-repair-service.svg
  next/src/assets/icons-olo/material-location-away.svg
  next/src/assets/icons-olo/material-pedal-bike.svg
  next/src/assets/icons-olo/material-recycling.svg
  next/src/assets/icons-olo/material-shopping-bag.svg
  next/src/assets/icons-olo/material-smart-toy.svg
  next/src/assets/icons-olo/material-styler.svg
  next/src/assets/icons-olo/material-takeout-dining.svg
  next/src/assets/icons-olo/material-tour.svg
  next/src/components/common/Icon/OloIcon.tsx
Labels: pr: fix & ship :ship:

#628 #405 Detail page - career position
  .prettierrc
  next/.env.example
  next/package.json
  next/public/locales/sk/translation.json
  next/src/assets/icons-olo/career-place.svg
  next/src/assets/icons-olo/career-salary.svg
  next/src/assets/icons-olo/career-time.svg
  next/src/assets/icons-olo/index.ts
  next/src/assets/icons/pomoc.svg
  next/src/components/common/Card/CareerRowCard.stories.tsx
  next/src/components/common/Card/CareerRowCard.tsx
  next/src/components/common/Icon/OloIcon.tsx
  next/src/components/sections/VacanciesSection.tsx
  next/src/pages/api/nalgoo-detail.ts
  next/src/pages/career/[id].tsx
  next/src/services/nalgoo/fetchOpenPositions.ts
  next/src/services/nalgoo/fetchOpenPositionsFromApi.ts
  next/src/services/nalgoo/fetchPositionsDetail.ts
  next/src/services/nalgoo/fetchPositionsDetailFromApi.ts
  next/src/services/nalgoo/utils.ts
  next/tailwind.config.ts
  next/yarn.lock
Labels: pr: fix & ship :ship:

#675 Update config-sync files
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##items.location-cards-item.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.form-cta-banner.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.table.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.waste-collection-points.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##page.page.json
Labels: pr: fix & ship :ship:

#661 #635 Enable fullscreen display of iframe section
  next/src/components/sections/IframeSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.cards-list.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.iframe-section.json
  strapi/schema.graphql
  strapi/src/components/sections/iframe-section.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#676 Add field to track page content state #micromanagement
  next/src/services/graphql/api.ts
  strapi/config/sync/admin-role.admin-lztq8g5p.json
  strapi/config/sync/admin-role.strapi-super-admin.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##branch.branch.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##content-owner.content-owner.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##page.page.json
  strapi/schema.graphql
  strapi/src/admin/app.tsx
  strapi/src/api/content-owner/content-types/content-owner/schema.json
  strapi/src/api/content-owner/controllers/content-owner.ts
  strapi/src/api/content-owner/routes/content-owner.ts
  strapi/src/api/content-owner/services/content-owner.ts
  strapi/src/api/page/content-types/page/schema.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#685 Quickfix spacings and alignments in Richtext
  next/src/components/formatting/Markdown.module.scss
  next/src/components/formatting/Markdown.tsx
  next/src/components/sections/RichtextSection.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#686 671 globalsearchsection small fixes
  next/src/assets/pictograms/elektronicke-sluzby.svg
  next/src/assets/pictograms/index.tsx
  next/src/assets/pictograms/transparentne-mesto.svg
  next/src/components/common/Card/SearchResultRowCard.tsx
  next/src/components/common/Icon/Pictogram.tsx
  next/src/services/meili/fetchers/servicesFetcher.ts
  next/src/services/nalgoo/fetchOpenPositions.ts
  next/src/services/nalgoo/fetchPositionsDetail.ts
Labels: pr: fix & ship :ship:

#687 Fix ArticleCard height when in row
  next/src/components/common/Card/ArticleCard.tsx
  next/src/components/sections/homepage/ArticlesHomepageSection.tsx
Labels: pr: fix & ship :ship:

#682 #669 Prevent slider image from falling down on animating
  next/src/components/common/Slider/Slider.stories.tsx
  next/src/components/common/Slider/Slider.tsx
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#689 Add richtext field description into the wysiwyg plugin
  strapi/src/plugins/wysiwyg/admin/src/components/Wysiwyg/index.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#694 #607 Fix sidebar display bug
  next/src/components/layout/Sections.tsx
  next/src/pages/[...path].tsx
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#688 #652 Small changes in document detail page header
  next/public/locales/sk/translation.json
  next/src/components/sections/headers/DocumentPageHeader.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#668 #483 Adjust DocumentsSection items behaviour and design
  next/public/locales/sk/translation.json
  next/src/components/common/Card/FileRowCard.tsx
  next/src/components/common/Card/FileRowGroup.stories.tsx
  next/src/components/sections/DocumentsAllSection.tsx
  next/src/components/sections/DocumentsSection.tsx
  next/src/components/sections/FilesSection.tsx
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.documents.json
Labels: pr: fix & ship :ship:

#700 #600 Set-up Plausible analytics
  next/next.config.mjs
  next/package.json
  next/src/pages/_app.tsx
  next/yarn.lock
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#690 #643 ArticlesSection select by category or tag
  next/public/locales/sk/translation.json
  next/src/components/common/SearchResults/SearchResults.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/ArticlesSection.tsx
  next/src/components/sections/GlobalSearchSection.tsx
  next/src/components/sections/articles/ArticlesSection.tsx
  next/src/components/sections/articles/ArticlesSectionAll.tsx
  next/src/components/sections/articles/ArticlesSectionFiltered.tsx
  next/src/components/sections/headers/PageHeaderPickupDay.tsx
  next/src/components/sections/homepage/ArticlesHomepageSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/articles.gql
  next/src/services/meili/fetchers/articlesFetcher.ts
  strapi/config/plugins.meilisearch.config.ts
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.articles.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##article.article.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##document.document.json
  strapi/schema.graphql
  strapi/src/components/sections/articles.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#692 #650 remove redundant document fields
  next/public/locales/sk/translation.json
  next/src/components/page-contents/document/DocumentPageContent.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/documents.gql
  strapi/config/sync/admin-role.admin-lztq8g5p.json
  strapi/config/sync/admin-role.strapi-super-admin.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##document.document.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##tag.tag.json
  strapi/schema.graphql
  strapi/src/api/document/content-types/document/schema.json
  strapi/src/api/tag/content-types/tag/schema.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#709 iframe-resizer acknowledgement
  README.md
Labels: pr: fix & ship :ship:

#712 #672 RichText and Sidebar alignment
  next/src/components/sections/RichtextSection.tsx
Labels: pr: fix & ship :ship:

#713 Use Query Engine API createMany to bulk import waste collection days
  strapi/src/plugins/waste-collection-days-import/admin/src/components/ImportSection.tsx
  strapi/src/plugins/waste-collection-days-import/server/controllers/index.ts
Labels: pr: fix & ship :ship:

#711 Minor fixes in collection days tables
  next/src/components/formatting/Markdown.tsx
  next/src/components/sections/WasteCollectionDays.tsx
Labels: pr: fix & ship :ship:

#587 #531 Create menu for mobile devices
  next/public/locales/sk/translation.json
  next/src/components/common/Box/DirectionsBox.tsx
  next/src/components/common/Card/BasicRowCard.tsx
  next/src/components/common/Card/MenuItemArticleCard.tsx
  next/src/components/common/Card/MenuItemBranchCard.tsx
  next/src/components/common/Card/MenuItemWorkshopCard.tsx
  next/src/components/common/Icon/IconWrapper.tsx
  next/src/components/common/NavBar/MobileNavBar.tsx
  next/src/components/common/NavBar/MobileNavBarCurrentWeekMessage.tsx
  next/src/components/common/NavBar/MobileNavBarHeader/MobileNavBarHeader.tsx
  next/src/components/common/NavBar/MobileNavMenu/MobileNavMenu.tsx
  next/src/components/common/NavBar/MobileNavMenu/MobileNavMenuContent.tsx
  next/src/components/common/NavBar/MobileNavMenu/MobileNavMenuItem.tsx
  next/src/components/common/NavBar/MobileNavMenu/MobileNavMenuTrigger.tsx
  next/src/components/common/NavBar/NavBar.tsx
  next/src/components/common/NavBar/NavBarHeader/NavBarHeader.tsx
  next/src/components/common/NavBar/NavMenu/NavMenu.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuContextProvider.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuLatestArticlesList.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuLink.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuSingleColumnList.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuTrigger.tsx
  next/src/components/common/Pagination/PaginationWithInput.tsx
  next/src/components/common/SearchBar/SearchBar.tsx
  next/src/components/common/Tag/Tag.tsx
  next/src/components/layout/PageLayout.tsx
  next/src/services/graphql/api.ts
  next/src/utils/getTailwindBreakpointValue.ts
  next/src/utils/useTailwindBreakpointValue.ts
  next/tailwind.config.ts
Labels: pr: fix & ship :ship:

#715 #695 Article Category selection handling in "Aktuality" page
  next/public/locales/sk/translation.json
  next/src/components/sections/DocumentsAllSection.tsx
  next/src/components/sections/ServicesSection.tsx
  next/src/components/sections/articles/ArticlesSectionAll.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#701 Add headers to Nalgoo endpoints
  next/.env.example
  next/.gitignore
  next/next.config.mjs
  next/package.json
  next/src/components/common/Card/CareerRowCard.tsx
  next/src/pages/api/nalgoo-detail.ts
  next/src/pages/api/nalgoo.ts
  next/src/pages/career/[id].tsx
  next/src/services/nalgoo/fetchOpenPositions.ts
  next/src/services/nalgoo/fetchOpenPositionsFromApi.ts
  next/src/services/nalgoo/fetchPositionsDetail.ts
  next/src/services/nalgoo/fetchPositionsDetailFromApi.ts
  next/src/services/nalgoo/utils.ts
Labels: pr: fix & ship :ship:

#716 #531 Fix mobile header display
  next/src/components/common/NavBar/MobileNavBarHeader/MobileNavBarHeader.tsx
  next/tailwind.config.ts
Labels: pr: fix & ship :ship:

#720 #632 WasteCollectionDays section styling and finishing touches
  next/src/components/layout/Section/SectionHeader.tsx
  next/src/components/sections/WasteCollectionDays.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/meili/fetchers/wasteCollectionDaysFetcher.ts
  strapi/schema.graphql
  strapi/src/components/sections/waste-collection-days.json
  strapi/types/generated/components.d.ts
Labels: pr: needs review :pray:

#722 Use city account URL from envs
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/src/pages/form/[slug].tsx
Labels: pr: fix & ship :ship:

#724 Remove dev from iframe URL
  next/src/pages/form/[slug].tsx
Labels: pr: fix & ship :ship:

#717 #696 Implement URL query for serviceCategory selection in ServicesSection
  next/src/components/sections/ServicesSection.tsx
  next/src/services/meili/fetchers/servicesFetcher.ts
  strapi/config/plugins.meilisearch.config.ts
Labels: pr: fix & ship :ship:

#704 Set-up tailwindcss-animate
  next/package.json
  next/tailwind.config.ts
  next/yarn.lock
Labels: pr: fix & ship :ship:

#729 Bump @iframe-resizer/react
  next/package.json
  next/yarn.lock
Labels: pr: fix & ship :ship:

#731 #714 add sidebar to workshops
  next/src/pages/workshops/[slug].tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/workshops.gql
  strapi/config/sync/admin-role.strapi-super-admin.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##workshop.workshop.json
  strapi/schema.graphql
  strapi/src/api/workshop/content-types/workshop/schema.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#735 #728 Fix link target in useGetLinkProps
  next/src/utils/useGetLinkProps.ts
Labels: pr: fix & ship :ship:

#736 #733 Fix justifying content in LocationCard
  next/src/components/common/Card/LocationCard.tsx
Labels: pr: fix & ship :ship:

#737 #707 Fix several minor things mentioned in issue
  next/src/components/sections/articles/ArticlesSectionFiltered.tsx
  next/src/components/sections/headers/PageHeaderPickupDay.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_header-sections.gql
  next/src/services/graphql/queries/articles.gql
  next/src/services/meili/fetchers/articlesFetcher.ts
  strapi/config/plugins.meilisearch.config.ts
Labels: pr: fix & ship :ship:

#718 #558 Refactor menu cards
  next/src/components/common/Card/MenuItemArticleCard.tsx
  next/src/components/common/Card/MenuItemBranchCard.tsx
  next/src/components/common/Card/MenuItemWorkshopCard.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuLink.tsx
Labels: pr: fix & ship :ship:

#742 #405 - Fix paddings in Career position detail page
  next/src/components/common/Card/CareerRowCard.tsx
  next/src/pages/career/[id].tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#739 #626 Remove redundant validity field + add inReview page internal state
  next/public/locales/sk/translation.json
  next/src/components/sections/WasteCollectionDays/WasteCollectionDaysSectionTabs.tsx
  next/src/components/sections/WasteCollectionDays/WasteCollectionDaysTable.tsx
  next/src/components/sections/headers/PageHeaderPickupDay.stories.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/waste-collection-days.gql
  strapi/schema.graphql
  strapi/src/admin/app.tsx
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/api/waste-collection-day/content-types/waste-collection-day/schema.json
  strapi/src/components/header-sections/pickup-day.json
  strapi/src/components/sections/waste-collection-days.json
  strapi/src/plugins/waste-collection-days-import/server/helpers/parse-waste-collection-days-xlsx.ts
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#738 #626 WasteCollectionDays section - validity tabs
  next/public/locales/sk/translation.json
  next/src/components/layout/Sections.tsx
  next/src/components/sections/WasteCollectionDays.tsx
  next/src/components/sections/WasteCollectionDays/WasteCollectionDays.tsx
  next/src/components/sections/WasteCollectionDays/WasteCollectionDaysSectionContent.tsx
  next/src/components/sections/WasteCollectionDays/WasteCollectionDaysSectionTabs.tsx
  next/src/components/sections/WasteCollectionDays/WasteCollectionDaysTable.tsx
  next/src/components/sections/WasteCollectionDays/WasteCollectionDaysValidityMessage.tsx
  next/src/components/sections/headers/PageHeaderPickupDay.stories.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/waste-collection-days.gql
  next/src/services/meili/fetchers/wasteCollectionDaysFetcher.ts
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.waste-collection-days.json
  strapi/schema.graphql
  strapi/src/admin/app.tsx
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/api/waste-collection-day/content-types/waste-collection-day/schema.json
  strapi/src/components/header-sections/pickup-day.json
  strapi/src/components/sections/waste-collection-days.json
  strapi/src/plugins/waste-collection-days-import/server/helpers/parse-waste-collection-days-xlsx.ts
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#613 #557 Josephine integration
  next/.env.example
  next/kubernetes/base/deployment.yml
  next/kubernetes/envs/Dev/.env
  next/kubernetes/envs/Dev/kustomization.yml
  next/kubernetes/envs/Dev/secrets/josephine.secret.yml
  next/kubernetes/envs/Prod/.env
  next/kubernetes/envs/Prod/kustomization.yml
  next/kubernetes/envs/Prod/secrets/josephine.secret.yml
  next/kubernetes/envs/Staging/.env
  next/kubernetes/envs/Staging/kustomization.yml
  next/kubernetes/envs/Staging/secrets/josephine.secret.yml
  next/package.json
  next/public/locales/sk/translation.json
  next/src/components/common/Table/Table.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/ProcurementsSection.tsx
  next/src/pages/api/josephine.ts
  next/src/pages/form/index.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/josephine/fetchProcurements.ts
  next/src/services/josephine/fetchProcurementsFromApi.ts
  next/src/services/josephine/josephineTypes.ts
  next/src/services/josephine/utils.tsx
  next/src/utils/formatPrice.ts
  next/yarn.lock
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/procurements.json
  strapi/src/components/sections/vacancies.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:
