Repository bratislava/olo.sk, pull requests merged in 2024-05, with the labels that each got.

#96 Add PageHeaderBasic
  next/src/_components/sections/PageHeader/PageHeaderBasic.stories.tsx
  next/src/_components/sections/PageHeader/PageHeaderBasic.tsx
Labels: pr: fix & ship :ship:

#95 Setup fonts #47
  next/public/fonts/FrutigerLTPro-Black.otf
  next/public/fonts/FrutigerLTPro-BlackCn.otf
  next/public/fonts/FrutigerLTPro-BlackCnIta.otf
  next/public/fonts/FrutigerLTPro-BlackItalic.otf
  next/public/fonts/FrutigerLTPro-Bold.otf
  next/public/fonts/FrutigerLTPro-BoldCn.otf
  next/public/fonts/FrutigerLTPro-BoldCnIta.otf
  next/public/fonts/FrutigerLTPro-BoldItalic.otf
  next/public/fonts/FrutigerLTPro-Condensed.otf
  next/public/fonts/FrutigerLTPro-CondensedIta.otf
  next/public/fonts/FrutigerLTPro-ExtraBlackCn.otf
  next/public/fonts/FrutigerLTPro-ExtraBlkCnIta.otf
  next/public/fonts/FrutigerLTPro-Italic.otf
  next/public/fonts/FrutigerLTPro-Light.otf
  next/public/fonts/FrutigerLTPro-LightCn.otf
  next/public/fonts/FrutigerLTPro-LightCnIta.otf
  next/public/fonts/FrutigerLTPro-LightItalic.otf
  next/public/fonts/FrutigerLTPro-Roman.otf
  next/public/fonts/FrutigerLTPro-UltraBlack.otf
  next/src/_components/common/Button/Button.tsx
  next/src/_components/common/Link/Link.stories.tsx
  next/src/_components/common/Link/Link.tsx
  next/src/_components/common/Pagination/Pagination.tsx
  next/src/_components/common/Typography/Typography.stories.tsx
  next/src/pages/_app.tsx
  next/src/pages/index.tsx
  next/src/styles/globals.css
Labels: pr: fix & ship :ship:

#98 Accordion #54
  next/package.json
  next/src/_components/common/Accordion/Accordion.stories.tsx
  next/src/_components/common/Accordion/Accordion.tsx
  next/src/_components/common/Accordion/AccordionGroup.stories.tsx
  next/src/_components/common/Accordion/AccordionGroup.tsx
  next/src/_components/common/Accordion/AnimateHeight.tsx
  next/yarn.lock
Labels: pr: needs work :hammer_and_wrench:

#99 #68 Add richtext section
  next/package.json
  next/src/_components/common/Typography/Typography.tsx
  next/src/_components/layout/BlocksRenderer.tsx
  next/src/_components/layout/Sections.tsx
  next/src/_components/sections/RichtextSection.tsx
  next/src/_components/sections/Section1.tsx
  next/src/pages/index.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/yarn.lock
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/richtext.json
  strapi/src/components/sections/section-1.json
  strapi/src/components/sections/section-2.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#105 #104 Add and display Homepage content type
  next/src/pages/index.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/homepage.gql
  strapi/.strapi/client/app.js
  strapi/package.json
  strapi/schema.graphql
  strapi/src/api/homepage/content-types/homepage/schema.json
  strapi/src/api/homepage/controllers/homepage.ts
  strapi/src/api/homepage/routes/homepage.ts
  strapi/src/api/homepage/services/homepage.ts
  strapi/src/components/items/slide.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#106 #33 Fix styles in Typography
  next/src/_components/common/Button/Button.tsx
  next/src/_components/common/Typography/Typography.tsx
  next/src/styles/globals.css
  next/tailwind.config.ts
Labels: pr: fix & ship :ship:

#108 #109 Fix typescript validation pipeline
  .github/workflows/deploy.yml
  .github/workflows/validate.yml
Labels: pr: needs review :pray:

#101 Modal #61
  next/.storybook/i18n.js
  next/.storybook/preview.tsx
  next/package.json
  next/public/locales/sk/translation.json
  next/src/_components/common/Icon/Icon.tsx
  next/src/_components/common/ModalDialog/Dialog.tsx
  next/src/_components/common/ModalDialog/Modal.tsx
  next/src/_components/modals/ModalShare.stories.tsx
  next/src/_components/modals/ModalShare.tsx
  next/src/assets/icons/facebook.svg
  next/src/assets/icons/index.ts
  next/src/assets/icons/linkedin.svg
  next/src/assets/icons/twitter.svg
  next/tailwind.config.ts
  next/yarn.lock
Labels: pr: fix & ship :ship:, pr: question :question:

#111 #110 Storybook tidy up
  next/src/_components/common/Accordion/Accordion.stories.tsx
  next/src/_components/common/Accordion/AccordionGroup.tsx
  next/src/_components/common/Card/ArticleCard.stories.tsx
  next/src/_components/common/Card/BasicCard.stories.tsx
  next/src/_components/common/Card/BranchCard.stories.tsx
  next/src/_components/common/Card/CategoryCard.stories.tsx
  next/src/_components/common/Card/FaqCategoryCard.stories.tsx
  next/src/_components/common/Card/HomepageMainTile.stories.tsx
  next/src/_components/common/Card/HomepageSmallTile.stories.tsx
  next/src/_components/common/Card/ListingCard.stories.tsx
  next/src/_components/common/Card/LocationCard.stories.tsx
  next/src/_components/common/Card/SearchResultRowCard.stories.tsx
  next/src/_components/common/Card/WasteSortingCard.stories.tsx
  next/src/_components/common/Card/WorkshopCard.stories.tsx
  next/src/_components/common/Icon/Icon.stories.tsx
  next/src/_components/common/Icon/Pictogram.stories.tsx
  next/src/_components/common/Tag/Tag.stories.tsx
  next/src/_components/modals/ModalShare.tsx
Labels: pr: fix & ship :ship:

#113 Upgrade Strapi to v4.24.2
  strapi/package.json
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#114 #93 Cards update - add translations, aria labels, refactor CardBase
  next/public/locales/sk/translation.json
  next/src/_components/common/Card/ArticleCard.stories.tsx
  next/src/_components/common/Card/ArticleCard.tsx
  next/src/_components/common/Card/ArticleRowCard.stories.tsx
  next/src/_components/common/Card/ArticleRowCard.tsx
  next/src/_components/common/Card/BasicCard.stories.tsx
  next/src/_components/common/Card/BasicCard.tsx
  next/src/_components/common/Card/BranchCard.stories.tsx
  next/src/_components/common/Card/BranchCard.tsx
  next/src/_components/common/Card/CardBase.stories.tsx
  next/src/_components/common/Card/CardBase.tsx
  next/src/_components/common/Card/CategoryCard.stories.tsx
  next/src/_components/common/Card/CategoryCard.tsx
  next/src/_components/common/Card/DocumentRowCard.stories.tsx
  next/src/_components/common/Card/DocumentRowCard.tsx
  next/src/_components/common/Card/FaqCategoryCard.stories.tsx
  next/src/_components/common/Card/FaqCategoryCard.tsx
  next/src/_components/common/Card/HomepageMainTile.stories.tsx
  next/src/_components/common/Card/HomepageMainTile.tsx
  next/src/_components/common/Card/HomepageSmallTile.stories.tsx
  next/src/_components/common/Card/HomepageSmallTile.tsx
  next/src/_components/common/Card/JobPositionRowCard.tsx
  next/src/_components/common/Card/ListingCard.stories.tsx
  next/src/_components/common/Card/ListingCard.tsx
  next/src/_components/common/Card/LocationCard.stories.tsx
  next/src/_components/common/Card/LocationCard.tsx
  next/src/_components/common/Card/MenuItemArticleCard.stories.tsx
  next/src/_components/common/Card/MenuItemArticleCard.tsx
  next/src/_components/common/Card/MenuItemWorkshopCard.stories.tsx
  next/src/_components/common/Card/MenuItemWorkshopCard.tsx
  next/src/_components/common/Card/SearchResultRowCard.stories.tsx
  next/src/_components/common/Card/SearchResultRowCard.tsx
  next/src/_components/common/Card/WasteSortingCard.stories.tsx
  next/src/_components/common/Card/WasteSortingCard.tsx
  next/src/_components/common/Card/WorkshopCard.stories.tsx
  next/src/_components/common/Card/WorkshopCard.tsx
  next/src/_components/common/Icon/Icon.tsx
  next/src/_components/common/Pagination/Pagination.tsx
  next/src/_components/common/Typography/Typography.tsx
  next/src/assets/icons/index.ts
  next/src/assets/icons/live_help.svg
  next/src/assets/icons/place.svg
Labels: pr: fix & ship :ship:

#116 #58 Row groups
  next/src/_components/common/Accordion/Accordion.tsx
  next/src/_components/common/Accordion/AccordionGroup.tsx
  next/src/_components/common/Card/DocumentRowCard.tsx
  next/src/_components/common/Card/DocumentRowGroup.stories.tsx
  next/src/_components/common/Card/DocumentRowGroup.tsx
Labels: pr: fix & ship :ship:

#117 #63 Banner
  next/src/_components/common/Banner/Banner.stories.tsx
  next/src/_components/common/Banner/Banner.tsx
  next/src/_components/common/Button/Button.tsx
  next/src/_components/common/Card/CardImage.tsx
  next/src/_components/common/Card/WasteSortingCard.tsx
  next/src/_components/common/Icon/Icon.tsx
  next/src/_components/common/Icon/Pictogram.tsx
  next/src/_components/common/ImagePlaceholder.tsx
  next/src/_components/common/Spinner/Spinner.tsx
  next/src/assets/images/index.ts
  next/src/assets/images/placeholder-abstract-background.png
  next/src/assets/images/zevo-iron-hand.jpg
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#119 #70 Ordered Cards Section
  next/index.d.ts
  next/src/_components/layout/Sections.tsx
  next/src/_components/sections/OrderedCardsSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/tailwind.config.ts
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/items/ordered-cards-item.json
  strapi/src/components/sections/ordered-cards.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#120 #69 Section: Image + Text
  next/next.config.mjs
  next/src/_components/layout/Sections.tsx
  next/src/_components/sections/ImageAndTextSection.tsx
  next/src/_utils/getLinkProps.ts
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_common.gql
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/items/link.json
  strapi/src/components/sections/image-and-text.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#121 Add storybook deployment
  .github/workflows/deploy.yml
  next/.gitignore
  next/Dockerfile.storybook
  next/kubernetes/base/deployment.yml
  next/kubernetes/base/ingress.yml
  next/kubernetes/base/kustomization.yml
  next/kubernetes/base/service-storybook.yml
  next/kubernetes/base/storybook-nginx-conf.yml
Labels: pr: fix & ship :ship:

#122 #71 Columned Items Section
  next/src/_components/layout/Section/SectionHeader.tsx
  next/src/_components/layout/Sections.tsx
  next/src/_components/sections/ColumnsSection.tsx
  next/src/_components/sections/ImageAndTextSection.tsx
  next/src/_components/sections/OrderedCardsSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/items/columns-item.json
  strapi/src/components/sections/columns.json
  strapi/src/components/sections/image-and-text.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#127 #66 Add BranchesSection
  next/src/_components/layout/Sections.tsx
  next/src/_components/sections/BranchesSection.tsx
  next/src/_utils/isDefined.ts
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/branches.gql
  strapi/schema.graphql
  strapi/src/api/branch/content-types/branch/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/branches.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#126 #72 Image And Text Overlapped Section
  next/src/_components/layout/Sections.tsx
  next/src/_components/sections/ImageAndTextOverlappedSection.tsx
  next/src/_components/sections/ImageAndTextSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/image-and-text-overlapped.json
  strapi/src/components/sections/image-and-text.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#128 #67 Add WorkshopsSection
  next/src/_components/layout/Sections.tsx
  next/src/_components/sections/WorkshopsSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/workshops.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/api/workshop/content-types/workshop/schema.json
  strapi/src/api/workshop/controllers/workshop.ts
  strapi/src/api/workshop/routes/workshop.ts
  strapi/src/api/workshop/services/workshop.ts
  strapi/src/components/sections/workshops.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#135 Fix storybook image tagging when ran outside of release
  .github/workflows/deploy.yml
  next/kubernetes/base/deployment.yml
Labels: pr: needs review :pray:
