Repository bratislava/olo.sk, pull requests merged in 2024-08, with the labels that each got.

#257 #186 Add Radix components into Mega Menu
  next/public/locales/sk/translation.json
  next/src/components/common/NavBar/MobileNavBar.tsx
  next/src/components/common/NavBar/NavBarHeader/NavBarHeader.tsx
  next/src/components/common/NavBar/NavBarLogo.tsx
  next/src/components/common/NavBar/NavMenu/NavMenu.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuContent.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuContentCell.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuContentDivider.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuItem.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuLink.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuTrigger.tsx
  next/src/components/common/NavBar/NavMenu/getParsedMenus.ts
  next/src/components/layout/PageLayout.tsx
  next/src/components/placeholder/NavMenuPlaceholder.tsx
  next/src/components/placeholder/PlaceholderWrapper.tsx
  next/src/components/placeholder/usePlaceholderMenuData.ts
  next/src/pages/_app.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#293 #186 Silence A11Y warnings
  next/src/components/common/NavBar/NavMenu/NavMenuContent.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
Labels: pr: fix & ship :ship:

#287 Restore Basic header in Strapi
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/header-sections/basic.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#294 Remove basic header from strapi
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/header-sections/basic.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#298 7# detail pages
  next/public/locales/sk/translation.json
  next/src/assets/icons-olo/chat.svg
  next/src/assets/icons-olo/index.ts
  next/src/components/common/Badge/Badge.stories.tsx
  next/src/components/common/Badge/Badge.tsx
  next/src/components/common/Banner/Banner.tsx
  next/src/components/common/Card/DocumentRowCard.stories.tsx
  next/src/components/common/Card/DocumentRowGroup.stories.tsx
  next/src/components/common/Card/FileRowCard.stories.tsx
  next/src/components/common/Card/FileRowCard.tsx
  next/src/components/common/Card/FileRowGroup.stories.tsx
  next/src/components/common/Card/FileRowGroup.tsx
  next/src/components/common/Card/ServiceCard.stories.tsx
  next/src/components/common/Card/ServiceCard.tsx
  next/src/components/common/FaqGroup/FaqGroup.tsx
  next/src/components/common/Icon/OloIcon.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/page-contents/document/DocumentPageContent.tsx
  next/src/components/page-contents/service/ServicePageContent.tsx
  next/src/components/page-contents/service/ServiceSidebarPlaceholder.tsx
  next/src/components/placeholder/HomePageContentPlaceholder.tsx
  next/src/components/sections/BannerSection.tsx
  next/src/components/sections/FaqSection.tsx
  next/src/components/sections/FilesSection.tsx
  next/src/components/sections/WorkshopsSection.stories.tsx
  next/src/components/sections/headers/DocumentPageHeader.tsx
  next/src/components/sections/headers/ServicePageHeader.tsx
  next/src/pages/[...path].tsx
  next/src/pages/documents/[slug].tsx
  next/src/pages/faq-categories/[slug].tsx
  next/src/pages/services/[slug].tsx
  next/src/pages/workshops/[slug].tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_categories-and-tags.gql
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/documents.gql
  next/src/services/graphql/queries/services.gql
  next/src/services/graphql/queries/workshops.gql
  next/src/utils/getPageBreadcrumbs.ts
  strapi/schema.graphql
  strapi/src/api/document/content-types/document/schema.json
  strapi/src/api/faq-category/content-types/faq-category/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/api/service-category/content-types/service-category/schema.json
  strapi/src/api/service/content-types/service/schema.json
  strapi/src/api/workshop/content-types/workshop/schema.json
  strapi/src/components/sections/banner.json
  strapi/src/components/sections/faq.json
  strapi/src/components/sections/files.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#318 #317 Add TableSection table placeholder and fix anchorPill scroll behavior
  next/src/components/common/AnchorPill/AnchorPill.tsx
  next/src/components/placeholder/PlaceholderWrapper.tsx
  next/src/components/sections/TableSection.tsx
Labels: pr: fix & ship :ship:

#305 #203 Add iconName variant for OrderedCardsSection cards
  next/src/components/common/Card/BasicRowCard.tsx
  next/src/components/sections/OrderedCardsSection.stories.tsx
  next/src/components/sections/OrderedCardsSection.tsx
  next/src/components/sections/headers/PageHeaderIcon.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/components/items/ordered-cards-item.json
  strapi/src/components/sections/ordered-cards.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#303 #276 Fix icon in HomepageSmallTile
  next/src/components/common/Card/HomepageSmallTile.tsx
  next/src/components/sections/hompage/HeroHomepageSection.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#300 #278 Columns list - replace text with richtext
  next/src/components/sections/ColumnsListSection.stories.tsx
  next/src/components/sections/ColumnsListSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/components/items/columns-list-item.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#302 #301 Add CardsListSection and refactor related components
  next/public/locales/sk/translation.json
  next/src/components/common/Card/ListingCard.stories.tsx
  next/src/components/common/Card/ListingCard.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/page-contents/service/ServicePageContent.tsx
  next/src/components/sections/CardsListSection.tsx
  next/src/components/sections/WorkshopsSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/api/service/content-types/service/schema.json
  strapi/src/components/items/cards-list-item.json
  strapi/src/components/sections/cards-list.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#324 #324 Correct Markdown renderer styling, especially tables
  next/src/components/formatting/Markdown.module.scss
  next/src/components/formatting/Markdown.tsx
  next/src/utils/useHorizontalScrollFade.ts
Labels: pr: fix & ship :ship:

#328 #176 Add next env variables to storybook config
  next/.storybook/index.d.ts
  next/.storybook/main.ts
Labels: pr: fix & ship :ship:

#281 #144 Setup meilisearch (WIP)
  docker-compose.yml
  next/kubernetes/base/deployment.yml
  next/kubernetes/envs/Dev/config.json
  next/kubernetes/envs/Prod/config.json
  next/kubernetes/envs/Staging/config.json
  next/package.json
  next/src/services/meili/fetchers/articlesFetcher.ts
  next/src/services/meili/fetchers/pagesFetcher.ts
  next/src/services/meili/meiliClient.ts
  next/src/services/meili/types.ts
  next/src/services/meili/utils.ts
  next/src/utils/getPagePath.ts
  next/src/utils/useGetFullPath.ts
  next/yarn.lock
  strapi/.strapi/client/app.js
  strapi/config/plugins.meilisearch.config.ts
  strapi/kubernetes/base/.meilisearch.env
  strapi/kubernetes/base/deployment.yml
  strapi/kubernetes/base/ingress.yml
  strapi/kubernetes/base/kustomization.yml
  strapi/kubernetes/base/service-meilisearch.yml
  strapi/kubernetes/base/stateful-set-meilisearch.yml
  strapi/kubernetes/envs/Dev/config.json
  strapi/kubernetes/envs/Dev/kustomization.yml
  strapi/kubernetes/envs/Dev/secrets/meilisearch.secret.yml
  strapi/kubernetes/envs/Prod/config.json
  strapi/kubernetes/envs/Prod/kustomization.yml
  strapi/kubernetes/envs/Prod/secrets/meilisearch.secret.yml
  strapi/kubernetes/envs/Staging/config.json
  strapi/kubernetes/envs/Staging/kustomization.yml
  strapi/kubernetes/envs/Staging/secrets/meilisearch.secret.yml
  strapi/package.json
  strapi/yarn.lock
Labels: pr: needs review :pray:

#296 #186 Implement Megamenu enhancements
  next/public/locales/sk/translation.json
  next/src/components/common/Card/MenuItemArticleCard.tsx
  next/src/components/common/Card/MenuItemBranchCard.stories.tsx
  next/src/components/common/Card/MenuItemBranchCard.tsx
  next/src/components/common/Card/MenuItemWorkshopCard.tsx
  next/src/components/common/NavBar/DesktopNavBar.tsx
  next/src/components/common/NavBar/MobileNavBar.tsx
  next/src/components/common/NavBar/NavBarDivider.tsx
  next/src/components/common/NavBar/NavBarHeader/NavBarHeader.tsx
  next/src/components/common/NavBar/NavBarLogo.tsx
  next/src/components/common/NavBar/NavBarMobileCurrentWeekMessage.tsx
  next/src/components/common/NavBar/NavMenu/NavBarHorizontalDivider.tsx
  next/src/components/common/NavBar/NavMenu/NavMenu.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuContent.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuContentCell.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuContentDivider.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuLatestArticlesSection.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuTrigger.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuTwoColumnSection.tsx
  next/src/components/common/NavBar/NavMenu/splitNavMenuSectionLinks.ts
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/workshops.gql
  next/src/utils/cn.ts
  next/src/utils/getLatestWorkshopDateAsISOString.ts
  next/src/utils/useGetLinkProps.ts
  next/src/utils/useMostRecentWorkshopDate.ts
  next/src/utils/useSectionGrouper.ts
  strapi/schema.graphql
  strapi/src/api/workshop/content-types/workshop/schema.json
  strapi/src/components/items/workshop-date.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#321 #310 faq categories section
  next/src/components/layout/Sections.tsx
  next/src/components/sections/BranchesSection.tsx
  next/src/components/sections/FaqCategoriesSection.tsx
  next/src/components/sections/TableSection.tsx
  next/src/components/sections/WorkshopsSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/faq-categories.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#325 #201 Add ServicesSection
  next/public/locales/sk/translation.json
  next/src/components/common/Card/ServiceCard.tsx
  next/src/components/common/Chip/Chip.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/ServicesSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/services.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#326 #307 WasteSortingCardsSection
  next/src/assets/pictograms/index.tsx
  next/src/assets/pictograms/waste-cemetery.svg
  next/src/assets/pictograms/waste-christmas-trees.svg
  next/src/components/common/Card/WasteSortingCard.stories.tsx
  next/src/components/common/Card/WasteSortingCard.tsx
  next/src/components/common/Icon/Pictogram.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/WasteSortingCardsSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/styles/colors.css
  next/tailwind.config.ts
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/items/waste-sorting-cards-item.json
  strapi/src/components/sections/waste-sorting-cards.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#327 #289 Articles section
  next/package.json
  next/public/locales/sk/translation.json
  next/src/components/common/Pagination/PaginationWithInput.tsx
  next/src/components/common/SearchBar/SearchBar.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/ArticlesSection.tsx
  next/src/pages/_app.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/articles.gql
  next/tailwind.config.ts
  next/yarn.lock
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/articles.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#332 #186 Modify Strapi schema for Workshop
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/workshops.gql
  strapi/schema.graphql
  strapi/src/components/items/workshop-date.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#335 #186 Create a placeholder for Workshop dates
  next/src/utils/getLatestWorkshopDateAsISOString.ts
  next/src/utils/useMostRecentWorkshopDate.ts
Labels: pr: fix & ship :ship:

#359 #358 Make whole links clickable in Menu
  next/src/components/common/NavBar/NavMenu/NavMenuLink.tsx
Labels: pr: fix & ship :ship:

#363 #362 Unify sections title and text setup
  next/src/components/layout/Section/SectionHeader.tsx
  next/src/components/sections/ArticlesSection.tsx
  next/src/components/sections/BannerSection.tsx
  next/src/components/sections/ColumnsListSection.tsx
  next/src/components/sections/DocumentsSection.tsx
  next/src/components/sections/FaqCategoriesSection.tsx
  next/src/components/sections/FaqSection.tsx
  next/src/components/sections/FilesSection.tsx
  next/src/components/sections/ImageAndTextOverlappedSection.stories.tsx
  next/src/components/sections/ImageAndTextOverlappedSection.tsx
  next/src/components/sections/ImageAndTextSection.tsx
  next/src/components/sections/OrderedCardsSection.tsx
  next/src/components/sections/ServicesSection.tsx
  next/src/components/sections/TableSection.tsx
  next/src/components/sections/WasteSortingCardsSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/components/sections/articles.json
  strapi/src/components/sections/branches.json
  strapi/src/components/sections/cards-list.json
  strapi/src/components/sections/columns-list.json
  strapi/src/components/sections/columns.json
  strapi/src/components/sections/faq.json
  strapi/src/components/sections/files.json
  strapi/src/components/sections/image-and-text-overlapped.json
  strapi/src/components/sections/image-and-text.json
  strapi/src/components/sections/ordered-cards.json
  strapi/src/components/sections/table.json
  strapi/src/components/sections/workshops.json
  strapi/types/generated/components.d.ts
Labels: pr: needs review :pray:

#333 Fix Storybook deployment
  .github/workflows/deploy.yml
  next/Dockerfile.storybook
Labels: pr: needs review :pray:

#365 Add BAQueryClientProvider to Storybook
  next/.storybook/preview.tsx
Labels: pr: needs review :pray:

#366 #362 Change text type to long text in Columns section
  strapi/src/components/sections/columns.json
  strapi/types/generated/components.d.ts
Labels: pr: needs review :pray:

#367 Change richtext editor background to white
  strapi/src/plugins/wysiwyg/admin/src/components/Editor/index.tsx
Labels: pr: fix & ship :ship:

#371 #361 Implement Documents search section
  next/public/locales/sk/translation.json
  next/src/components/common/Card/SearchResultRowCard.tsx
  next/src/components/common/SearchBar/SearchBar.tsx
  next/src/components/sections/DocumentsAllSection.tsx
  next/src/components/sections/DocumentsSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/documents.gql
  next/src/services/meili/fetchers/documentsFetcher.ts
  next/src/utils/useRoutePreservedState.ts
  strapi/schema.graphql
  strapi/src/components/sections/branches.json
  strapi/src/components/sections/documents.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#370 #370 richtext tables features
  strapi/src/plugins/wysiwyg/patches/@wysimark+react+3.0.20.patch
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#374 #141 Prepare homepage slider
  next/src/components/sections/hompage/HeroHomepageSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/homepage.gql
Labels: pr: needs review :pray:

#368 #284 Create HalfBanner component
  next/src/components/common/Banner/Banner.stories.tsx
  next/src/components/common/Banner/HalfBanner.stories.tsx
  next/src/components/common/Banner/HalfBanner.tsx
  next/src/components/sections/hompage/KoloHomepageSection.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#369 #284 Edit KOLO homepage section in Strapi
  next/src/components/sections/hompage/KoloHomepageSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/homepage.gql
  strapi/schema.graphql
  strapi/src/components/sections/kolo-homepage-section.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#345 #186 Format workshop dates in Mega Menu
  next/public/locales/sk/translation.json
  next/src/components/common/Card/MenuItemWorkshopCard.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
  next/src/utils/formatMostRecentWorkshopDate.ts
  next/src/utils/getLatestWorkshopDateAsISOString.ts
  next/src/utils/useMostRecentWorkshopDate.ts
Labels: pr: fix & ship :ship:

#372 #352 Add Strapi Header component into Menu
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/menu.gql
  strapi/schema.graphql
  strapi/src/api/menu/content-types/menu/schema.json
  strapi/src/components/items/menu-header.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#376 #354 Consolidate unordered list in Menu into a single element
  next/src/components/common/NavBar/NavMenu/NavMenuTwoColumnSection.tsx
  next/src/components/common/NavBar/NavMenu/splitNavMenuSectionLinks.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:, pr: question :question:

#389 #382 Add banner to WasteSortingCardsSection
  next/src/components/sections/WasteSortingCardsSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/components/sections/waste-sorting-cards.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#388 #387 Fix table overflow fade
  next/src/components/formatting/Markdown.tsx
  next/src/pages/_app.tsx
  next/src/styles/table.scss
Labels: pr: fix & ship :ship:

#395 #306 Add Sorting guide sections
  next/src/components/common/Accordion/Accordion.stories.tsx
  next/src/components/common/Accordion/Accordion.tsx
  next/src/components/common/Accordion/AccordionGroup.stories.tsx
  next/src/components/common/Accordion/WasteIcon.tsx
  next/src/components/common/Accordion/WasteSortingGuide.stories.tsx
  next/src/components/common/Accordion/WasteSortingGuide.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/SortingGuideAccordionsSection.tsx
  next/src/components/sections/SortingGuideSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/items/sorting-guide-accordion-item.json
  strapi/src/components/items/sorting-guide-item.json
  strapi/src/components/items/sorting-guide.json
  strapi/src/components/sections/sorting-guide-accordions.json
  strapi/src/components/sections/sorting-guide.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#385 #193 CardSliderSection
  next/src/components/common/Card/BasicCard.stories.tsx
  next/src/components/common/Card/BasicCard.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/CardSliderSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/api/service/content-types/service/schema.json
  strapi/src/components/items/card-slider-card.json
  strapi/src/components/sections/card-slider.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#408 Minor translation fix
  next/public/locales/sk/translation.json
  next/src/components/common/Gallery/Gallery.tsx
  next/src/components/sections/DocumentsAllSection.tsx
Labels: pr: fix & ship :ship:

#409 Fix typo in documents relation name
  next/src/services/graphql/api.ts
  strapi/schema.graphql
  strapi/src/api/document-category/content-types/document-category/schema.json
  strapi/src/api/document/content-types/document/schema.json
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#377 #357 Mega Menu clean-up
  next/src/components/common/NavBar/NavBarDivider.tsx
  next/src/components/common/NavBar/NavMenu/NavMenu.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuContent.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuContentCell.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuLatestArticlesSection.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuLink.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuSectionLink.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuTwoColumnSection.tsx
  next/src/utils/cn.ts
  next/src/utils/getNavMenuCells.ts
  next/src/utils/useSectionGrouper.ts
Labels: pr: fix & ship :ship:

#412 #403 Add Contacts Section and Opening Hours Section
  next/src/components/common/Card/ContactRowCard.tsx
  next/src/components/common/ContactBox.tsx
  next/src/components/common/OpeningHoursBox.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/ContactsSection.tsx
  next/src/components/sections/OpeningTimesSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/contacts.gql
  next/tailwind.config.ts
  strapi/schema.graphql
  strapi/src/api/contact/content-types/contact/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/contacts.json
  strapi/src/components/sections/opening-times.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#415 #141 Improve homepage slider layout
  next/src/components/sections/hompage/HeroHomepageSection.tsx
  next/tailwind.config.ts
Labels: pr: needs review :pray:

#420 Add missing or wrong Strapi translations into app.tsx config
  strapi/src/admin/app.tsx
Labels: pr: needs review :pray:

#397 #355 Retrieve the subText property from links
  next/src/components/common/NavBar/NavMenu/NavMenuSectionLink.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/workshops.gql
  next/src/utils/formatMostRecentWorkshopDate.ts
  next/src/utils/useGetLinkProps.ts
Labels: pr: fix & ship :ship:

#411 #353 Rename hasDivider field in Strapi
  next/src/components/common/NavBar/NavMenu/NavMenuContent.tsx
  next/src/components/common/NavBar/NavMenu/getParsedMenus.ts
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/menu.gql
  strapi/schema.graphql
  strapi/src/components/menu/menu-section.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#418 Improve Spinner styling
  next/src/components/common/Button/Button.tsx
  next/src/components/common/SearchBar/SearchBar.tsx
  next/src/components/common/Spinner/Spinner.stories.tsx
  next/src/components/common/Spinner/Spinner.tsx
Labels: pr: fix & ship :ship:

#419 Upgrade strapi to v4.25.8 and apply patch to @strapi/admin to have cl…
  strapi/README.md
  strapi/package.json
  strapi/patches/@strapi+admin+4.25.8.patch
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#429 Upgrade i18n
  next/.eslintrc.js
  next/package.json
  next/src/components/common/Accordion/Accordion.stories.tsx
  next/src/components/common/Accordion/AccordionGroup.stories.tsx
  next/src/components/common/Card/BasicRowCard.stories.tsx
  next/src/components/common/Card/CardBase.stories.tsx
  next/src/components/common/Card/ContactRowCard.stories.tsx
  next/src/components/common/Card/PersonContactRowCard.stories.tsx
  next/src/components/common/Tag/Tag.stories.tsx
  next/src/components/modals/share/ShareModal.stories.tsx
  next/src/components/page-contents/service/ServiceSidebarPlaceholder.tsx
  next/src/components/placeholder/HomePageContentPlaceholder.tsx
  next/yarn.lock
Labels: pr: fix & ship :ship:

#431 Upgrade tailwind related packages and run lint fix
  next/.eslintrc.js
  next/package.json
  next/src/components/common/Breadcrumbs/MobileBreadcrumbs.tsx
  next/src/components/common/Card/FileRowCard.tsx
  next/src/components/common/Carousel/Carousel.tsx
  next/src/components/common/Footer/MobileFooter.tsx
  next/src/components/formatting/Markdown.tsx
  next/src/components/sections/CardsListSection.tsx
  next/src/components/sections/FaqCategoriesSection.tsx
  next/src/components/sections/ServicesSection.tsx
  next/src/components/sections/WorkshopsSection.tsx
  next/src/components/sections/headers/HeaderTitleText.tsx
  next/src/components/sections/headers/PageHeaderFeaturedNews.tsx
  next/src/components/sections/headers/PageHeaderGallery.tsx
  next/yarn.lock
Labels: pr: fix & ship :ship:

#434 #342 Richtext image aspectratio fix
  next/src/components/common/Accordion/Accordion.tsx
  next/src/components/common/AnchorPill/AnchorPill.tsx
  next/src/components/common/Card/BasicCard.tsx
  next/src/components/common/Card/BranchCard.stories.tsx
  next/src/components/common/Card/BranchCard.tsx
  next/src/components/common/Card/MenuItemArticleCard.tsx
  next/src/components/common/Card/SearchResultRowCard.tsx
  next/src/components/common/Gallery/Gallery.tsx
  next/src/components/common/Icon/Icon.stories.tsx
  next/src/components/common/Icon/OloIcon.stories.tsx
  next/src/components/common/Icon/Pictogram.stories.tsx
  next/src/components/formatting/Markdown.tsx
  next/src/components/modals/gallery/GallerySlider.tsx
  next/src/components/modals/gallery/ImageLightBox.tsx
  next/src/components/page-contents/service/ServicePageContent.tsx
  next/src/components/sections/DocumentsAllSection.tsx
  next/src/components/sections/headers/PageHeaderSideImage.tsx
  next/src/components/sections/hompage/KoloHomepageSection.tsx
Labels: pr: fix & ship :ship:

#443 #349 Fix table width
  next/src/components/formatting/Markdown.tsx
Labels: pr: fix & ship :ship:

#445 #437 Add FormCtaBanner to Sections
  next/src/components/layout/Sections.tsx
Labels: pr: fix & ship :ship:

#446 #442 Add linkedin icon to the Footer
  next/src/assets/icons-olo/index.ts
  next/src/assets/icons-olo/social-media-linkedin-footer.svg
  next/src/components/common/Footer/FooterShared.tsx
  next/src/components/common/Footer/MobileFooter.tsx
  next/src/components/common/Icon/OloIcon.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/footer.gql
  strapi/schema.graphql
  strapi/src/api/footer/content-types/footer/schema.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:
