Repository bratislava/olo.sk, pull requests merged in 2024-07, with the labels that each got.

#171 #169 Placeholder layouts
  next/src/assets/images/olo-logo.svg
  next/src/components/placeholder/FooterPlaceholder.tsx
  next/src/components/placeholder/HomePageContentPlaceholder.tsx
  next/src/components/placeholder/NavBarPlaceholder.tsx
  next/src/components/placeholder/PageLayoutPlaceholder.tsx
  next/src/components/placeholder/PlaceholderWrapper.tsx
  next/src/pages/articles/[slug].tsx
  next/src/pages/index.tsx
  next/src/pages/pages/[slug].tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#175 Remove PickupDay story
  next/src/components/sections/headers/PageHeaderPickupDay.stories.tsx
Labels: pr: fix & ship :ship:

#209 #166 Update branch card and section design
  next/src/components/common/Card/BranchCard.tsx
  next/src/components/sections/BranchesSection.stories.tsx
  next/src/components/sections/BranchesSection.tsx
Labels: pr: fix & ship :ship:

#214 #188 Create Badge component
  next/public/locales/sk/translation.json
  next/src/components/common/Badge/Badge.stories.tsx
  next/src/components/common/Badge/Badge.tsx
  next/src/styles/colors.css
  next/tailwind.config.ts
Labels: pr: fix & ship :ship:

#219 #53 Breadcrumbs
  next/public/locales/sk/translation.json
  next/src/components/common/Breadcrumbs/Breadcrumbs.tsx
  next/src/components/common/Breadcrumbs/DesktopBreadcrumbs.tsx
  next/src/components/common/Breadcrumbs/MobileBreadcrumbs.tsx
  next/src/components/placeholder/BreadcrumbsPlaceholder.tsx
  next/src/components/placeholder/HomePageContentPlaceholder.tsx
  next/src/components/placeholder/NavBarPlaceholder.tsx
  next/src/components/sections/headers/PageHeaderFeaturedNews.tsx
  next/src/components/sections/headers/PageHeaderPickupDay.tsx
  next/src/middleware.ts
  next/src/pages/[...path].tsx
  next/src/pages/articles/[slug].tsx
  next/src/pages/pages/[slug].tsx
Labels: pr: fix & ship :ship:

#210 #182 BasicRowCard
  next/.storybook/main.ts
  next/src/components/common/Card/BasicRowCard.stories.tsx
  next/src/components/common/Card/BasicRowCard.tsx
  next/src/components/common/Card/CareerRowCard.stories.tsx
  next/src/components/common/Card/CareerRowCard.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#211 #183 ContactRowCard
  next/package.json
  next/public/locales/sk/translation.json
  next/src/components/common/Card/ContactRowCard.stories.tsx
  next/src/components/common/Card/ContactRowCard.tsx
  next/src/components/common/Card/PersonContactRowCard.stories.tsx
  next/src/components/common/Card/PersonContactRowCard.tsx
  next/src/components/common/Icon/Icon.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_common.gql
  next/src/utils/formatFileExtension.ts
  next/src/utils/formatFileSize.ts
  next/src/utils/useGetDownloadAriaLabel.tsx
  next/yarn.lock
  strapi/schema.graphql
  strapi/src/components/items/file-item.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#222 #184 Sidebar
  next/src/assets/icons-olo/directions.svg
  next/src/assets/icons-olo/index.ts
  next/src/components/common/Card/BasicRowCard.tsx
  next/src/components/common/Card/ContactRowCard.tsx
  next/src/components/common/Icon/OloIcon.tsx
  next/src/components/common/Sidebar/SidebarCareer.stories.tsx
  next/src/components/common/Sidebar/SidebarCareer.tsx
  next/src/components/common/Sidebar/SidebarContacts.stories.tsx
  next/src/components/common/Sidebar/SidebarContacts.tsx
  next/src/components/common/Sidebar/SidebarDivider.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#221 #178 Create ServiceCard component
  next/src/components/common/Card/ServiceCard.stories.tsx
  next/src/components/common/Card/ServiceCard.tsx
Labels: pr: fix & ship :ship:

#223 174# footer
  next/public/locales/sk/translation.json
  next/src/assets/icons-olo/index.ts
  next/src/assets/icons-olo/social-media-facebook-footer.svg
  next/src/assets/icons-olo/social-media-instagram-footer.svg
  next/src/components/common/Accordion/Accordion.tsx
  next/src/components/common/Accordion/AccordionGroup.tsx
  next/src/components/common/Card/ListingCard.tsx
  next/src/components/common/Footer/DesktopFooter.tsx
  next/src/components/common/Footer/Footer.tsx
  next/src/components/common/Footer/FooterShared.tsx
  next/src/components/common/Footer/MobileFooter.tsx
  next/src/components/common/Icon/OloIcon.tsx
  next/src/components/placeholder/FooterPlaceholder.tsx
  next/src/components/placeholder/HomePageContentPlaceholder.tsx
  next/src/components/placeholder/PageLayoutPlaceholder.tsx
  next/src/pages/articles/[slug].tsx
  next/src/pages/index.tsx
  next/src/pages/pages/[slug].tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_general.gql
  next/src/services/graphql/queries/pages.gql
  next/tailwind.config.ts
  strapi/schema.graphql
  strapi/src/api/footer/content-types/footer/schema.json
  strapi/src/api/footer/controllers/footer.ts
  strapi/src/api/footer/routes/footer.ts
  strapi/src/api/footer/services/footer.ts
  strapi/src/components/items/footer-column.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#208 add link to product specification
  README.md
Labels: pr: fix & ship :ship:

#224 #56 Implement input-based pagination
  next/src/components/common/Input/Input.tsx
  next/src/components/common/Pagination/Pagination.tsx
  next/src/components/common/Pagination/PaginationInput.stories.tsx
  next/src/components/common/Pagination/PaginationInput.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#226 #158 RichtextSection, Richtext markdown renderer
  next/package.json
  next/src/components/common/Footer/FooterShared.tsx
  next/src/components/formatting/Markdown.module.scss
  next/src/components/formatting/Markdown.tsx
  next/src/components/sections/RichtextSection.tsx
  next/src/pages/articles/[slug].tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  next/src/services/graphql/queries/articles.gql
  next/yarn.lock
  strapi/schema.graphql
  strapi/src/api/article/content-types/article/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/richtext.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:, pr: question :question:

#228 #178 ServiceCard - minor fixes in styling
  next/src/components/common/Card/ServiceCard.stories.tsx
  next/src/components/common/Card/ServiceCard.tsx
Labels: pr: fix & ship :ship:

#230 #194 Add Faqs content type and locales where relevant
  next/src/components/placeholder/HomePageContentPlaceholder.tsx
  next/src/components/sections/headers/PageHeaderPickupDay.tsx
  next/src/pages/[...path].tsx
  next/src/pages/api/paths-list.ts
  next/src/pages/articles/[slug].tsx
  next/src/pages/index.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_general.gql
  next/src/services/graphql/queries/articles.gql
  next/src/services/graphql/queries/branches.gql
  next/src/services/graphql/queries/categories.gql
  next/src/services/graphql/queries/faqs.gql
  next/src/services/graphql/queries/pages.gql
  strapi/schema.graphql
  strapi/src/api/faq/content-types/faq/schema.json
  strapi/src/api/faq/controllers/faq.ts
  strapi/src/api/faq/routes/faq.ts
  strapi/src/api/faq/services/faq.ts
  strapi/src/api/footer/content-types/footer/schema.json
  strapi/src/api/homepage/content-types/homepage/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/api/router/content-types/router/schema.json
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#232 #231 Add Menu content type to Strapi
  next/src/services/graphql/queries/_general.gql
  next/src/services/graphql/queries/footer.gql
  next/src/services/graphql/queries/menu.gql
  strapi/schema.graphql
  strapi/src/api/menu/content-types/menu/schema.json
  strapi/src/api/menu/controllers/menu.ts
  strapi/src/api/menu/routes/menu.ts
  strapi/src/api/menu/services/menu.ts
  strapi/src/components/menu/menu-item.json
  strapi/src/components/menu/menu-link.json
  strapi/src/components/menu/menu-section.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#234 #217 Change Router to Sitemap content type
  next/src/pages/api/paths-list.ts
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_general.gql
  next/src/utils/useGetFullPath.ts
  strapi/schema.graphql
  strapi/src/api/router/content-types/router/schema.json
  strapi/src/api/router/controllers/router.ts
  strapi/src/api/router/routes/router.ts
  strapi/src/api/router/services/router.ts
  strapi/src/api/sitemap/content-types/sitemap/schema.json
  strapi/src/api/sitemap/controllers/sitemap.ts
  strapi/src/api/sitemap/routes/sitemap.ts
  strapi/src/api/sitemap/services/sitemap.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#229 #56 Input-based pagination - minor fixes
  next/src/components/common/Input/Input.tsx
  next/src/components/common/Pagination/Pagination.stories.tsx
  next/src/components/common/Pagination/PaginationInput.stories.tsx
  next/src/components/common/Pagination/PaginationInput.tsx
  next/src/components/common/Pagination/PaginationWithInput.tsx
  next/src/components/common/Pagination/usePaginationWithInput.ts
  next/src/styles/globals.css
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#225 #60 Add Map block component
  next/src/assets/icons-olo/directions-bus.svg
  next/src/assets/icons-olo/index.ts
  next/src/assets/icons-olo/local-parking.svg
  next/src/assets/images/index.ts
  next/src/assets/images/olo-placeholder-map.jpg
  next/src/components/common/Box/Map.stories.tsx
  next/src/components/common/Box/Map.tsx
  next/src/components/common/Icon/OloIcon.tsx
  next/src/components/common/MapPlaceholder.tsx
  next/src/components/common/Sidebar/SidebarCareer.tsx
  next/src/components/common/Sidebar/SidebarContacts.tsx
Labels: pr: fix & ship :ship:

#236 Fix middleware
  next/src/middleware.ts
  next/src/pages/api/paths-list.ts
  next/src/pages/api/sitemap/[...pathname].ts
Labels: pr: needs review :pray:

#240 #237 Use `iframe-resizer` library for embedded Konto iframe
  next/package.json
  next/src/pages/form.tsx
  next/src/pages/index.tsx
  next/yarn.lock
Labels: pr: fix & ship :ship:

#245 Update embedded form URL
  next/src/pages/form.tsx
Labels: pr: fix & ship :ship:

#255 Change form URL from dev to staging
  next/src/pages/form.tsx
Labels: pr: fix & ship :ship:

#246 #147 Implement Wysimark editor
  strapi/.strapi/client/app.js
  strapi/Dockerfile
  strapi/config/plugins.ts
  strapi/package.json
  strapi/src/admin/webpack.config.ts
  strapi/src/plugins/wysiwyg/README.md
  strapi/src/plugins/wysiwyg/admin/src/components/Editor/index.tsx
  strapi/src/plugins/wysiwyg/admin/src/components/Initializer/index.tsx
  strapi/src/plugins/wysiwyg/admin/src/components/MediaLib/index.tsx
  strapi/src/plugins/wysiwyg/admin/src/components/PluginIcon/index.tsx
  strapi/src/plugins/wysiwyg/admin/src/components/Wysiwyg/index.tsx
  strapi/src/plugins/wysiwyg/admin/src/index.tsx
  strapi/src/plugins/wysiwyg/admin/src/pages/App/index.tsx
  strapi/src/plugins/wysiwyg/admin/src/pages/HomePage/index.tsx
  strapi/src/plugins/wysiwyg/admin/src/pluginId.ts
  strapi/src/plugins/wysiwyg/admin/src/translations/en.json
  strapi/src/plugins/wysiwyg/admin/src/translations/fr.json
  strapi/src/plugins/wysiwyg/admin/src/utils/getTrad.ts
  strapi/src/plugins/wysiwyg/custom.d.ts
  strapi/src/plugins/wysiwyg/package.json
  strapi/src/plugins/wysiwyg/patches/@wysimark+react+3.0.20.patch
  strapi/src/plugins/wysiwyg/server/bootstrap.ts
  strapi/src/plugins/wysiwyg/server/config/index.ts
  strapi/src/plugins/wysiwyg/server/content-types/index.ts
  strapi/src/plugins/wysiwyg/server/controllers/index.ts
  strapi/src/plugins/wysiwyg/server/controllers/my-controller.ts
  strapi/src/plugins/wysiwyg/server/destroy.ts
  strapi/src/plugins/wysiwyg/server/index.ts
  strapi/src/plugins/wysiwyg/server/middlewares/index.ts
  strapi/src/plugins/wysiwyg/server/policies/index.ts
  strapi/src/plugins/wysiwyg/server/register.ts
  strapi/src/plugins/wysiwyg/server/routes/index.ts
  strapi/src/plugins/wysiwyg/server/services/index.ts
  strapi/src/plugins/wysiwyg/server/services/my-service.ts
  strapi/src/plugins/wysiwyg/strapi-admin.js
  strapi/src/plugins/wysiwyg/strapi-server.js
  strapi/src/plugins/wysiwyg/tsconfig.json
  strapi/src/plugins/wysiwyg/tsconfig.server.json
  strapi/src/plugins/wysiwyg/yarn.lock
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#238 #187 Create new accordion variant
  next/src/components/common/Accordion/Accordion.stories.tsx
  next/src/components/common/Accordion/Accordion.tsx
  next/src/components/common/Accordion/AccordionGroup.stories.tsx
  next/src/components/common/Accordion/AccordionGroup.tsx
  next/src/components/common/Accordion/WasteIcon.tsx
  next/src/components/common/Accordion/WasteSortingGuide.stories.tsx
  next/src/components/common/Accordion/WasteSortingGuide.tsx
  next/src/styles/globals.css
  next/tailwind.config.ts
Labels: pr: fix & ship :ship:

#241 #186 Create foundation for Mega Menu
  next/package.json
  next/public/locales/sk/translation.json
  next/src/components/common/NavBar/DesktopNavBar.tsx
  next/src/components/common/NavBar/MobileNavBar.tsx
  next/src/components/common/NavBar/NavBar.tsx
  next/src/components/common/NavBar/NavBarHeader/NavBarHeader.tsx
  next/src/components/common/NavBar/NavBarLogo.tsx
  next/src/components/common/NavBar/NavMenu/NavBarHorizontalDivider.tsx
  next/src/components/common/NavBar/NavMenu/NavMenu.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuContextProvider.tsx
  next/src/styles/globals.css
  next/src/utils/getCurrentWeekOfYear.ts
  next/src/utils/isCurrentWeekEven.ts
  next/src/utils/useCurrentWeekParity.ts
  next/yarn.lock
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#263 #256 Fix CardBase Height and Focus ring
  next/src/components/common/Card/CardBase.tsx
  next/src/components/common/Card/CardImage.tsx
Labels: pr: fix & ship :ship:

#260 Fix propagation of props in Button
  next/src/components/common/Button/Button.tsx
Labels: pr: fix & ship :ship:

#259 Add GeneralContextProvider to storybook
  next/.storybook/preview.tsx
  next/src/components/sections/headers/PageHeaderPickupDay.stories.tsx
Labels: pr: fix & ship :ship:

#264 Fix change from `category` to `articleCategory` in Article content type
  next/src/components/sections/headers/ArticlePageHeader.stories.tsx
  next/src/components/sections/headers/ArticlePageHeader.tsx
  next/src/components/sections/headers/PageHeaderFeaturedNews.tsx
  next/src/components/sections/headers/PageHeaderPickupDay.tsx
Labels: pr: fix & ship :ship:

#268 #261 Use also MenuLinkFragment in getLinkProps
  next/src/utils/useGetLinkProps.ts
Labels: pr: needs review :pray:

#270 #265 Add homepage sections
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/homepage.gql
  strapi/schema.graphql
  strapi/src/api/homepage/content-types/homepage/schema.json
  strapi/src/components/items/hero-main-tile.json
  strapi/src/components/items/hero-small-tile.json
  strapi/src/components/items/homepage-service-tile.json
  strapi/src/components/sections/articles-homepage-section.json
  strapi/src/components/sections/hero-homepage-section.json
  strapi/src/components/sections/kolo-homepage-section.json
  strapi/src/components/sections/services-homepage-section.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#272 #200 Homepage FE
  next/src/components/common/Card/HomepageMainTile.tsx
  next/src/components/common/Card/HomepageSmallTile.tsx
  next/src/components/layout/Section/SectionHeader.tsx
  next/src/components/sections/hompage/ArticlesHomepageSection.tsx
  next/src/components/sections/hompage/HeroHomepageSection.tsx
  next/src/components/sections/hompage/KoloHomepageSection.tsx
  next/src/components/sections/hompage/ServicesHomepageSection.tsx
  next/src/pages/index.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/homepage.gql
  next/src/utils/useGetLinkProps.ts
Labels: pr: fix & ship :ship:

#273 220/pageheaders refactor
  next/.storybook/preview.tsx
  next/src/components/common/Breadcrumbs/DesktopBreadcrumbs.tsx
  next/src/components/common/Card/BasicRowCard.tsx
  next/src/components/common/Card/DocumentRowCard.tsx
  next/src/components/common/Card/FaqCategoryCard.tsx
  next/src/components/common/Card/HomepageSmallTile.tsx
  next/src/components/common/Card/LocationCard.tsx
  next/src/components/common/Card/MenuItemWorkshopCard.tsx
  next/src/components/common/Card/SearchResultRowCard.tsx
  next/src/components/common/Card/WorkshopCard.tsx
  next/src/components/common/Icon/Icon.stories.tsx
  next/src/components/common/Icon/Icon.tsx
  next/src/components/common/Icon/OloIcon.stories.tsx
  next/src/components/common/Icon/OloIcon.tsx
  next/src/components/layout/PageHeaderSections.tsx
  next/src/components/layout/PageLayout.tsx
  next/src/components/placeholder/NavBarPlaceholder.tsx
  next/src/components/sections/headers/PageHeaderBasic.stories.tsx
  next/src/components/sections/headers/PageHeaderBasic.tsx
  next/src/components/sections/headers/PageHeaderFeaturedNews.stories.tsx
  next/src/components/sections/headers/PageHeaderFeaturedNews.tsx
  next/src/components/sections/headers/PageHeaderGallery.stories.tsx
  next/src/components/sections/headers/PageHeaderGallery.tsx
  next/src/components/sections/headers/PageHeaderIcon.stories.tsx
  next/src/components/sections/headers/PageHeaderIcon.tsx
  next/src/components/sections/headers/PageHeaderImage.stories.tsx
  next/src/components/sections/headers/PageHeaderImage.tsx
  next/src/components/sections/headers/PageHeaderPickupDay.stories.tsx
  next/src/components/sections/headers/PageHeaderPickupDay.tsx
  next/src/components/sections/headers/PageHeaderSideImage.stories.tsx
  next/src/components/sections/headers/PageHeaderSideImage.tsx
  next/src/components/sections/hompage/KoloHomepageSection.tsx
  next/src/pages/[...path].tsx
  next/src/pages/articles/[slug].tsx
  next/src/pages/documents/[slug].tsx
  next/src/pages/faq-categories/[slug].tsx
  next/src/pages/form.tsx
  next/src/pages/index.tsx
  next/src/pages/services/[slug].tsx
  next/src/pages/workshops/[slug].tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_header-sections.gql
  next/src/utils/getCurrentWeekOfYear.ts
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/header-sections/basic.json
  strapi/src/components/header-sections/featured-news.json
  strapi/src/components/header-sections/gallery.json
  strapi/src/components/header-sections/icon.json
  strapi/src/components/header-sections/image.json
  strapi/src/components/header-sections/pickup-day.json
  strapi/src/components/header-sections/side-image.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#280 #194 Add FaqSection
  next/src/components/layout/Section/SectionHeader.tsx
  next/src/components/layout/Sections.tsx
  next/src/components/sections/FaqSection.stories.tsx
  next/src/components/sections/FaqSection.tsx
  next/src/services/graphql/api.ts
  next/src/services/graphql/queries/_page-sections.gql
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/faq.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#277 #204 Implement ServicesTile component
  next/src/components/common/Card/ServicesTile.stories.tsx
  next/src/components/common/Card/ServicesTile.tsx
  next/src/components/sections/hompage/KoloHomepageSection.tsx
  next/src/components/sections/hompage/ServicesHomepageSection.tsx
Labels: pr: fix & ship :ship:
